export { StageCanvas } from './StageCanvas';
export type { StageCanvasProps, StageStatus } from './StageCanvas';
export type { StageProjector } from './three/StageScene';
export { Playhead } from './timeline/Playhead';
export type { PlayheadSnapshot } from './timeline/Playhead';
export { buildBeatTable, locate, completedStep, beatSeconds, BEAT_SECONDS, STAGGER_SECONDS } from './timeline/beats';
export type { BeatTable, BeatPosition } from './timeline/beats';
export { usePlayhead, usePlayheadTime } from './timeline/usePlayhead';
export { StageModel } from './model/StageModel';
export { StageSample, sampleStage } from './model/sampler';
export { cameraAt } from './model/camera';
export { STAGE_PALETTES, contrastRatio, relativeLuminance, edgeColorFor } from './look/palette';
export type { StageTheme, StagePalette, StateColor } from './look/palette';
export { STATE_TREATMENTS } from './look/treatments';
export type { StateTreatment } from './look/treatments';
export { ATTENTION_BUDGET, MUTATION_KINDS, allocateAttention, isMutation } from './motion/attention';
export { springResidual, springProgress, settleTime, massFor } from './motion/spring';
export { QUALITY, initialTier } from './three/quality';
export type { QualityTier } from './three/quality';
export type { StageFonts } from './three/LabelLayer';
export { WORLDS, WORLD_IDS, isStageWorld, hasCast } from './worlds/types';
export type { StageWorld, WorldInfo } from './worlds/types';
export { WORLD_PALETTES, paletteFor } from './worlds/palettes';
export { sampleCast, stationsAt, poseFor, createCast, CREW_SIZE } from './worlds/cast';
export type { CastMember, CastPose, CastGait, CastStyle, Station } from './worlds/cast';
export { perfExtras, perfMonitorEnabled } from './three/perf';
