/**
 * AQVL Example Registry
 * ─────────────────────────────────────────────────────────────────
 * Single source of truth for all playground examples.
 *
 * To add a new example:
 *   1. Add its AQVL source to the appropriate Library file in this
 *      directory (or create a new one).
 *   2. Append an entry to the EXAMPLES array below.
 *
 * The Example Explorer reads exclusively from this registry.
 * ─────────────────────────────────────────────────────────────────
 */

import { SortingScripts }    from './SortingLibrary';
import { ArrayScripts }      from './ArrayLibrary';
import { LinkedListScripts } from './LinkedListLibrary';
import { SearchingScripts }  from './SearchingLibrary';
import { TreeScripts }       from './TreeLibrary';
import { LoopScripts }       from './LoopLibrary';
import { StackScripts }      from './StackLibrary';
import { QueueScripts }      from './QueueLibrary';
import { GraphScripts }      from './GraphLibrary';
import { HeapScripts }       from './HeapLibrary';
import { HashMapScripts }    from './HashMapLibrary';
import { TrieScripts }       from './TrieLibrary';
import { RecursionScripts }  from './RecursionLibrary';
import { LayoutScripts }     from './LayoutLibrary';

// ── Types ──────────────────────────────────────────────────────────────────────

export type ExampleCategory =
  | 'Arrays'
  | 'Sorting'
  | 'Linked Lists'
  | 'Trees'
  | 'Searching'
  | 'Loops & Control'
  | 'Stacks'
  | 'Queues'
  | 'Graphs'
  | 'Heaps'
  | 'Hash Maps'
  | 'Tries'
  | 'Recursion & Functions'
  | 'Layout & Camera';

export interface Example {
  /** Unique, stable identifier (used as React key and for active-state tracking). */
  id: string;
  /** Human-readable name shown in the explorer list. */
  title: string;
  /** Category grouping for display in the explorer. */
  category: ExampleCategory;
  /** Short description of the algorithm or data structure. */
  description: string;
  /** Difficulty level of understanding the example. */
  difficulty: 'Easy' | 'Medium' | 'Hard';
  /** Full AQVL source code that will be loaded into the editor. */
  source: string;
}

// ── Registry ───────────────────────────────────────────────────────────────────

export const EXAMPLES: Example[] = [
  // ── Arrays ───────────────────────────────────────────────────────────────────
  {
    id: 'arrays-foundation',
    title: 'Array Foundation',
    category: 'Arrays',
    description: 'Core array operations: traversal, insertion, deletion, update, swap, and a linear search.',
    difficulty: 'Easy',
    source: ArrayScripts.ArrayFoundation,
  },
  {
    id: 'arrays-reverse',
    title: 'Reverse Array',
    category: 'Arrays',
    description: 'Reversing an array in-place using two pointers starting at opposite ends and swapping inwards.',
    difficulty: 'Easy',
    source: ArrayScripts.ArrayReverse,
  },
  {
    id: 'arrays-sliding-window',
    title: 'Sliding Window',
    category: 'Arrays',
    description: 'Finding the largest sum of k consecutive elements by sliding a window: add the entering element, subtract the leaving one.',
    difficulty: 'Medium',
    source: ArrayScripts.SlidingWindow,
  },
  {
    id: 'arrays-two-pointer',
    title: 'Two Pointer Pair Sum',
    category: 'Arrays',
    description: 'Finding a pair in a sorted array that sums to a target, moving whichever pointer brings the sum closer.',
    difficulty: 'Easy',
    source: ArrayScripts.TwoPointerPairSum,
  },
  {
    id: 'arrays-max-min',
    title: 'Find Maximum & Minimum',
    category: 'Arrays',
    description: 'Finding the largest and smallest elements in a single pass by tracking the best values seen so far.',
    difficulty: 'Easy',
    source: ArrayScripts.FindMaxMin,
  },
  {
    id: 'arrays-rotate',
    title: 'Rotate Array',
    category: 'Arrays',
    description: 'Rotating an array right by k places: save the last element, shift the rest right, place it at the front.',
    difficulty: 'Easy',
    source: ArrayScripts.RotateArrayRight,
  },
  {
    id: 'arrays-find-duplicate',
    title: 'Find Duplicate',
    category: 'Arrays',
    description: 'Detecting a duplicate value by comparing each element with every element after it, stopping at the first match.',
    difficulty: 'Easy',
    source: ArrayScripts.FindDuplicateInArray,
  },
  {
    id: 'arrays-merge-sorted',
    title: 'Merge Two Sorted Arrays',
    category: 'Arrays',
    description: 'Merging two sorted arrays into one by repeatedly taking the smaller front element, then copying the leftovers.',
    difficulty: 'Medium',
    source: ArrayScripts.MergeTwoSortedArrays,
  },
  {
    id: 'arrays-prefix-sum',
    title: 'Prefix Sum Array',
    category: 'Arrays',
    description: 'Building prefix[i] = prefix[i-1] + arr[i], then answering a range-sum query with a single subtraction.',
    difficulty: 'Easy',
    source: ArrayScripts.PrefixSumArray,
  },
  {
    id: 'arrays-move-zeroes',
    title: 'Move Zeroes to End',
    category: 'Arrays',
    description: 'Moving all zero elements to the end of an array while preserving the order of non-zero elements.',
    difficulty: 'Medium',
    source: ArrayScripts.MoveZeroesToEnd,
  },
  {
    id: 'arrays-dutch-flag',
    title: 'Dutch National Flag Sort',
    category: 'Arrays',
    description: 'Partitioning an array of 0s, 1s, and 2s into three groups in a single pass using three pointers.',
    difficulty: 'Hard',
    source: ArrayScripts.DutchNationalFlagSort,
  },

  // ── Sorting ──────────────────────────────────────────────────────────────────
  {
    id: 'sorting-bubble-sort',
    title: 'Bubble Sort',
    category: 'Sorting',
    description: 'Compare neighbours and swap when out of order; the largest value bubbles to the end each pass. Stops early when a pass makes no swap.',
    difficulty: 'Easy',
    source: SortingScripts.BubbleSort,
  },
  {
    id: 'sorting-selection-sort',
    title: 'Selection Sort',
    category: 'Sorting',
    description: 'Scan the unsorted part for its smallest value and swap it into place — one swap per pass, at most n - 1 swaps in total.',
    difficulty: 'Easy',
    source: SortingScripts.SelectionSort,
  },
  {
    id: 'sorting-insertion-sort',
    title: 'Insertion Sort',
    category: 'Sorting',
    description: 'Like sorting cards in your hand: pick up the next key, shift larger values right with a WHILE loop, drop the key into the gap.',
    difficulty: 'Easy',
    source: SortingScripts.InsertionSort,
  },
  {
    id: 'sorting-cocktail-shaker-sort',
    title: 'Cocktail Shaker Sort',
    category: 'Sorting',
    description: 'Bubble sort in both directions: forward passes push the largest value right, backward passes push the smallest value left.',
    difficulty: 'Easy',
    source: SortingScripts.CocktailShakerSort,
  },
  {
    id: 'sorting-quick-sort',
    title: 'Quick Sort',
    category: 'Sorting',
    description: 'Recursive divide and conquer: a Lomuto partition FUNCTION fixes the pivot in its final place, then each side is sorted recursively.',
    difficulty: 'Medium',
    source: SortingScripts.QuickSort,
  },
  {
    id: 'sorting-merge-sort',
    title: 'Merge Sort',
    category: 'Sorting',
    description: 'Recursively split the array in half, sort each half, then merge the two sorted halves through a temp array.',
    difficulty: 'Medium',
    source: SortingScripts.MergeSort,
  },
  {
    id: 'sorting-heap-sort',
    title: 'Heap Sort',
    category: 'Sorting',
    description: 'Build a max-heap inside the array with a siftDown FUNCTION, then repeatedly move the largest value to the end and repair the heap.',
    difficulty: 'Hard',
    source: SortingScripts.HeapSort,
  },
  {
    id: 'sorting-shell-sort',
    title: 'Shell Sort',
    category: 'Sorting',
    description: 'Insertion sort on elements a gap apart, halving the gap each round, so small values jump far left early.',
    difficulty: 'Medium',
    source: SortingScripts.ShellSort,
  },
  {
    id: 'sorting-counting-sort',
    title: 'Counting Sort',
    category: 'Sorting',
    description: 'No comparisons: tally every value in a counts array, then write each value back as many times as it was counted.',
    difficulty: 'Medium',
    source: SortingScripts.CountingSort,
  },
  {
    id: 'sorting-radix-sort',
    title: 'Radix Sort',
    category: 'Sorting',
    description: 'Sort by the ones digit, then the tens, then the hundreds — each round a stable counting sort on one digit.',
    difficulty: 'Hard',
    source: SortingScripts.RadixSort,
  },
  {
    id: 'sorting-cycle-sort',
    title: 'Cycle Sort',
    category: 'Sorting',
    description: 'Write every value straight into its final position (how many values are smaller), following each cycle round — the fewest possible writes.',
    difficulty: 'Hard',
    source: SortingScripts.CycleSort,
  },
  {
    id: 'sorting-pancake-sort',
    title: 'Pancake Sort',
    category: 'Sorting',
    description: 'The only move allowed is flipping the top of the stack: flip the biggest pancake to the top, then down to the bottom.',
    difficulty: 'Medium',
    source: SortingScripts.PancakeSort,
  },
  {
    id: 'sorting-exam-rank-list',
    title: 'Exam Rank List',
    category: 'Sorting',
    description: 'Sort marks highest-first while keeping roll numbers paired (parallel arrays), then print ranks with ties sharing a rank.',
    difficulty: 'Easy',
    source: SortingScripts.ExamRankList,
  },
  {
    id: 'sorting-leaderboard-insert',
    title: 'Game Leaderboard',
    category: 'Sorting',
    description: 'Keep a top-5 score board sorted as new scores arrive: one insertion step per score, and the lowest score drops off.',
    difficulty: 'Easy',
    source: SortingScripts.LeaderboardInsert,
  },
  {
    id: 'sorting-count-inversions',
    title: 'Count Inversions',
    category: 'Sorting',
    description: 'How unsorted is a ranking? Merge sort counts the out-of-order pairs while it sorts, in O(n log n).',
    difficulty: 'Hard',
    source: SortingScripts.CountInversions,
  },
  {
    id: 'sorting-quickselect-median',
    title: 'Median with Quickselect',
    category: 'Sorting',
    description: 'Find the k-th smallest value (the median delivery time) by partitioning only the side that can hold the answer.',
    difficulty: 'Hard',
    source: SortingScripts.QuickSelectKth,
  },
  {
    id: 'sorting-stable-sort-check',
    title: 'Sorted Check & Stability',
    category: 'Sorting',
    description: 'Check whether an array is already sorted, then sort products by price with a stable insertion sort — equal prices keep their order.',
    difficulty: 'Medium',
    source: SortingScripts.SortCheckAndStability,
  },

  // ── Linked Lists ──────────────────────────────────────────────────────────────
  {
    id: 'linked-list-singly',
    title: 'Singly Linked List',
    category: 'Linked Lists',
    description: 'Traverse with a curr pointer, insert at the head and tail, and delete a node by making its predecessor skip it — then FREE its memory.',
    difficulty: 'Easy',
    source: LinkedListScripts.SinglyLinkedList,
  },
  {
    id: 'linked-list-doubly',
    title: 'Doubly Linked List',
    category: 'Linked Lists',
    description: 'Walk forward with next and backward with prev, insert between two nodes (four pointer updates) and unlink a node in both directions.',
    difficulty: 'Easy',
    source: LinkedListScripts.DoublyLinkedList,
  },
  {
    id: 'linked-list-circular',
    title: 'Circular Linked List',
    category: 'Linked Lists',
    description: 'The tail points back to the head: loop once around the circle, append a node and delete the head while keeping the circle closed.',
    difficulty: 'Easy',
    source: LinkedListScripts.CircularLinkedList,
  },
  {
    id: 'linked-list-reverse',
    title: 'Reverse a Singly Linked List',
    category: 'Linked Lists',
    description: 'The classic in-place reversal: prev, curr and next pointers flip every arrow in one pass, O(n) time and O(1) space.',
    difficulty: 'Medium',
    source: LinkedListScripts.ReverseSinglyLinkedList,
  },
  {
    id: 'linked-list-reverse-doubly',
    title: 'Reverse a Doubly Linked List',
    category: 'Linked Lists',
    description: 'Reverse a doubly linked list by swapping every node\'s prev and next pointers, then verify it in both directions.',
    difficulty: 'Medium',
    source: LinkedListScripts.ReverseDoublyLinkedList,
  },
  {
    id: 'linked-list-reverse-circular',
    title: 'Reverse a Circular Linked List',
    category: 'Linked Lists',
    description: 'Flip every arrow of a circular list, stopping when the walk returns to the first node, then re-close the circle.',
    difficulty: 'Medium',
    source: LinkedListScripts.ReverseCircularLinkedList,
  },
  {
    id: 'linked-list-middle',
    title: 'Find the Middle Node',
    category: 'Linked Lists',
    description: 'Slow and fast pointers: fast moves two nodes for every one slow moves, so slow lands on the middle in a single pass.',
    difficulty: 'Easy',
    source: LinkedListScripts.FindMiddleNode,
  },
  {
    id: 'linked-list-detect-cycle',
    title: 'Detect & Remove a Cycle (Floyd)',
    category: 'Linked Lists',
    description: 'Floyd\'s tortoise and hare detects the cycle, finds the node where it starts, and breaks it.',
    difficulty: 'Hard',
    source: LinkedListScripts.DetectCycleFloyd,
  },
  {
    id: 'linked-list-merge-sorted',
    title: 'Merge Two Sorted Lists',
    category: 'Linked Lists',
    description: 'Walk two sorted lists side by side, always taking the smaller front value, to build one sorted list.',
    difficulty: 'Medium',
    source: LinkedListScripts.MergeTwoSortedLists,
  },
  {
    id: 'linked-list-remove-nth',
    title: 'Remove Nth Node From End',
    category: 'Linked Lists',
    description: 'Two pointers n nodes apart (plus a dummy node) find the nth node from the end in one pass; it is unlinked and freed.',
    difficulty: 'Medium',
    source: LinkedListScripts.RemoveNthFromEnd,
  },
  {
    id: 'linked-list-palindrome',
    title: 'Palindrome Linked List',
    category: 'Linked Lists',
    description: 'Find the middle, reverse the second half in place, compare the halves from both ends, then restore the list.',
    difficulty: 'Hard',
    source: LinkedListScripts.PalindromeLinkedList,
  },
  {
    id: 'linked-list-remove-duplicates',
    title: 'Remove Duplicates (Sorted List)',
    category: 'Linked Lists',
    description: 'Compare each node with its successor; duplicates are unlinked with one pointer write and freed.',
    difficulty: 'Easy',
    source: LinkedListScripts.RemoveDuplicates,
  },

  // ── Trees ─────────────────────────────────────────────────────────────────────
  {
    id: 'tree-basics',
    title: 'Binary Tree Basics',
    category: 'Trees',
    description: 'Build a binary tree node by node with NEW_NODE and left/right pointers, walk its leftmost and rightmost paths with a WHILE loop, then unlink and FREE a leaf.',
    difficulty: 'Easy',
    source: TreeScripts.BinaryTreeBasics,
  },
  {
    id: 'tree-traversals',
    title: 'Preorder, Inorder & Postorder',
    category: 'Trees',
    description: 'Three recursive traversal functions side by side: every call, return and visit is shown, with the call stack growing and shrinking beside the tree.',
    difficulty: 'Easy',
    source: TreeScripts.Traversals,
  },
  {
    id: 'tree-level-order',
    title: 'Level Order Traversal (BFS)',
    category: 'Trees',
    description: 'Breadth-first traversal with a real queue of node pointers: dequeue a node, enqueue its children, and print every level with its sum.',
    difficulty: 'Medium',
    source: TreeScripts.LevelOrder,
  },
  {
    id: 'tree-iterative-inorder',
    title: 'Iterative Inorder with a Stack',
    category: 'Trees',
    description: 'Inorder traversal without recursion: push the left spine onto a stack, pop, visit, go right. On a BST it lists the keys in sorted order.',
    difficulty: 'Medium',
    source: TreeScripts.IterativeInorder,
  },
  {
    id: 'tree-height-size',
    title: 'Height, Size & Leaf Count',
    category: 'Trees',
    description: 'Recursive functions that return values: the height, number of nodes and number of leaves, each computed from the answers of the two subtrees.',
    difficulty: 'Easy',
    source: TreeScripts.HeightSizeLeaves,
  },
  {
    id: 'tree-bst-insert-search',
    title: 'BST Search & Insert',
    category: 'Trees',
    description: 'Search a binary search tree by comparing and going left or right, and insert new keys by walking down with a parent pointer and linking a new node.',
    difficulty: 'Medium',
    source: TreeScripts.BSTSearchInsert,
  },
  {
    id: 'tree-bst-delete',
    title: 'BST Delete (All Three Cases)',
    category: 'Trees',
    description: 'Delete a leaf, a node with one child, and a node with two children (via its inorder successor) with real pointer relinking and FREE.',
    difficulty: 'Hard',
    source: TreeScripts.BSTDelete,
  },
  {
    id: 'tree-validate-bst',
    title: 'Validate a BST',
    category: 'Trees',
    description: 'Check whether a binary tree is a valid BST by passing a (low, high) range down the recursion — and see why comparing only parent and child is not enough.',
    difficulty: 'Medium',
    source: TreeScripts.ValidateBST,
  },
  {
    id: 'tree-lca',
    title: 'Lowest Common Ancestor (BST)',
    category: 'Trees',
    description: 'Find the lowest common ancestor of two keys by walking down from the root until they split to different sides.',
    difficulty: 'Medium',
    source: TreeScripts.LowestCommonAncestor,
  },
  {
    id: 'tree-mirror',
    title: 'Mirror (Invert) a Binary Tree',
    category: 'Trees',
    description: 'Recursively swap the left and right pointers of every node using a temp pointer, and watch the tree flip into its mirror image.',
    difficulty: 'Easy',
    source: TreeScripts.MirrorTree,
  },
  {
    id: 'tree-views',
    title: 'Left & Right Views',
    category: 'Trees',
    description: 'A level-by-level BFS that records the first and last node of every level: what you see looking at the tree from the left and from the right.',
    difficulty: 'Medium',
    source: TreeScripts.TreeViews,
  },
  {
    id: 'tree-path-sum',
    title: 'Root-to-Leaf Path Sum',
    category: 'Trees',
    description: 'Recursively search for a root-to-leaf path whose values add up to a target, subtracting as it goes and highlighting the path it finds.',
    difficulty: 'Medium',
    source: TreeScripts.PathSum,
  },

  // ── Searching ─────────────────────────────────────────────────────────────────
  // Every example is the real algorithm (low / high / mid, flags, WHILE,
  // recursive FUNCTIONs), with no hard-coded comparison steps.
  {
    id: 'searching-linear',
    title: 'Linear Search',
    category: 'Searching',
    description: 'Check every roll number from left to right until the target turns up, stopping early with a found flag; a second search for a missing roll number shows the worst case of n comparisons.',
    difficulty: 'Easy',
    source: SearchingScripts.LinearSearch,
  },
  {
    id: 'searching-all-occurrences',
    title: 'All Occurrences',
    category: 'Searching',
    description: 'Find every match instead of the first: walk the whole season of goals, collect each matching index into an array and remember the first and last match.',
    difficulty: 'Easy',
    source: SearchingScripts.AllOccurrences,
  },
  {
    id: 'searching-sentinel',
    title: 'Sentinel Linear Search',
    category: 'Searching',
    description: 'Copy the target into the last cell so the loop needs one check per step instead of two, then restore the shelf and tell a real match from the sentinel.',
    difficulty: 'Easy',
    source: SearchingScripts.SentinelLinearSearch,
  },
  {
    id: 'searching-binary',
    title: 'Binary Search',
    category: 'Searching',
    description: 'low / high / mid on a sorted price list: every step greys out the half that cannot hold the target. A hit, a hit at the edge, a miss, and the worst-case step count computed with a loop.',
    difficulty: 'Easy',
    source: SearchingScripts.BinarySearch,
  },
  {
    id: 'searching-binary-recursive',
    title: 'Recursive Binary Search',
    category: 'Searching',
    description: 'The same search as a recursive FUNCTION on chapter start pages: each call handles one window and calls itself on the half that can still contain the target.',
    difficulty: 'Medium',
    source: SearchingScripts.BinarySearchRecursive,
  },
  {
    id: 'searching-first-last',
    title: 'First & Last Occurrence',
    category: 'Searching',
    description: 'Binary search that keeps going after a match (left for the first copy, right for the last) to count how many students got the same mark in O(log n).',
    difficulty: 'Medium',
    source: SearchingScripts.FirstAndLastOccurrence,
  },
  {
    id: 'searching-insert-position',
    title: 'Search Insert Position',
    category: 'Searching',
    description: 'Lower-bound binary search finds where a new clinic appointment belongs, then INSERT puts it there so the list stays sorted; duplicates are rejected.',
    difficulty: 'Medium',
    source: SearchingScripts.SearchInsertPosition,
  },
  {
    id: 'searching-jump',
    title: 'Jump Search',
    category: 'Searching',
    description: 'Jump through sold seats in blocks of sqrt(n) (the square root found with a loop), then scan only the one block that can contain the seat.',
    difficulty: 'Medium',
    source: SearchingScripts.JumpSearch,
  },
  {
    id: 'searching-exponential',
    title: 'Exponential Search',
    category: 'Searching',
    description: 'Double the bound 1, 2, 4, 8 ... until it passes the target, then binary search only inside that range: fast when the target is near the front.',
    difficulty: 'Medium',
    source: SearchingScripts.ExponentialSearch,
  },
  {
    id: 'searching-ternary',
    title: 'Ternary Search',
    category: 'Searching',
    description: 'Two probes split the window into thirds and two thirds are thrown away each round.',
    difficulty: 'Medium',
    source: SearchingScripts.TernarySearch,
  },
  {
    id: 'searching-interpolation',
    title: 'Interpolation Search',
    category: 'Searching',
    description: 'Guess the probe position from the value (like opening a dictionary near the back for a word starting with w): one probe on evenly spaced house numbers, with the divide-by-zero case handled.',
    difficulty: 'Hard',
    source: SearchingScripts.InterpolationSearch,
  },
  {
    id: 'searching-rotated',
    title: 'Search a Rotated Sorted Array',
    category: 'Searching',
    description: 'Modified binary search on a sorted list that wraps around: decide which half is properly sorted, then whether the target lies inside it.',
    difficulty: 'Hard',
    source: SearchingScripts.RotatedArraySearch,
  },
  {
    id: 'searching-peak',
    title: 'Peak of a Trail',
    category: 'Searching',
    description: 'Binary search on the slope of a hiking trail that only climbs then only descends: climbing means the summit is to the right.',
    difficulty: 'Medium',
    source: SearchingScripts.PeakElement,
  },
  {
    id: 'searching-sqrt',
    title: 'Square Root by Binary Search',
    category: 'Searching',
    description: 'Binary search on the answer: find the largest r with r * r <= x for several numbers, counting the guesses.',
    difficulty: 'Medium',
    source: SearchingScripts.SquareRootSearch,
  },
  {
    id: 'searching-matrix',
    title: 'Search a Sorted Seat Map',
    category: 'Searching',
    description: 'A 3 x 4 cinema seat map stored row by row is one sorted list; binary search it and turn the position into row and column with division and remainder.',
    difficulty: 'Medium',
    source: SearchingScripts.SortedMatrixSearch,
  },
  {
    id: 'searching-missing-roll',
    title: 'Find the Missing Roll Number',
    category: 'Searching',
    description: 'Binary search for the first index where handedIn[i] != i + 1 to find the missing answer sheet without checking every sheet.',
    difficulty: 'Medium',
    source: SearchingScripts.MissingRollNumber,
  },
  {
    id: 'searching-ship-capacity',
    title: 'Delivery Truck Capacity',
    category: 'Searching',
    description: 'Binary search on the answer: the smallest truck capacity that ships all parcels in order within the allowed days, with a helper FUNCTION that simulates the days.',
    difficulty: 'Hard',
    source: SearchingScripts.ShipWithinDays,
  },
  {
    id: 'searching-contacts',
    title: 'Contact Book Search',
    category: 'Searching',
    description: 'Binary search on names in dictionary order, with a parallel array of phone extensions that is highlighted alongside the name.',
    difficulty: 'Easy',
    source: SearchingScripts.ContactBookSearch,
  },
  {
    id: 'searching-bst',
    title: 'BST Search Path',
    category: 'Searching',
    description: 'Search library book IDs in a binary search tree with a loop and with recursion, printing the path followed and the number of nodes compared.',
    difficulty: 'Medium',
    source: SearchingScripts.BSTSearch,
  },
  {
    id: 'searching-maze-dfs',
    title: 'Maze Exit with DFS',
    category: 'Searching',
    description: 'Recursive depth-first search that backs out of dead ends and stops as soon as the exit is reached, then rebuilds the way out from the parent pointers with a STACK.',
    difficulty: 'Medium',
    source: SearchingScripts.MazeDFS,
  },
  {
    id: 'searching-nearest-bfs',
    title: 'Nearest Hospital with BFS',
    category: 'Searching',
    description: 'Breadth-first search from home in rings of roads; the first hospital taken out of the queue is the nearest one, and the route is rebuilt from the parents.',
    difficulty: 'Medium',
    source: SearchingScripts.NearestHospitalBFS,
  },

  // ── Loops & Control ───────────────────────────────────────────────────────────
  // Every example is written out the long way (counters, flags, IF / ELSE IF
  // ladders, WHILE conditions, helper FUNCTIONs), with no shortcut built-ins.
  {
    id: 'loops-for-basics',
    title: 'For Loop Basics',
    category: 'Loops & Control',
    description: "LOOP i FROM 0 TO LENGTH(arr) - 1 visits every student's mark (both ends included), counts its own rounds, sums 1 to 10 and builds the even numbers from the loop variable.",
    difficulty: 'Easy',
    source: LoopScripts.ForLoopBasics,
  },
  {
    id: 'loops-while-digits',
    title: 'While Loop: Digits of a Number',
    category: 'Loops & Control',
    description: 'A WHILE loop peels digits off 90417 with % 10 until nothing is left: digit count, digit sum and the reversed number, plus a WHILE whose condition is false at the start and runs zero times.',
    difficulty: 'Easy',
    source: LoopScripts.WhileLoopDigits,
  },
  {
    id: 'loops-countdown-reverse',
    title: 'Counting Down & Reversing',
    category: 'Loops & Control',
    description: 'A WHILE countdown to lift-off, a LOOP that counts down by itself when TO < FROM, and two indices walking toward each other to reverse a playlist in place.',
    difficulty: 'Easy',
    source: LoopScripts.CountingDownAndReversing,
  },
  {
    id: 'loops-grade-calculator',
    title: 'IF / ELSE IF / ELSE: Grade Calculator',
    category: 'Loops & Control',
    description: 'A grading ladder checked top to bottom (only the first true branch runs), an invalid-mark check with OR, and a counter per grade.',
    difficulty: 'Easy',
    source: LoopScripts.GradeCalculator,
  },
  {
    id: 'loops-leap-year',
    title: 'Nested IFs & AND / OR: Leap Years',
    category: 'Loops & Control',
    description: 'The leap-year rule written twice, as nested IFs and as one AND / OR condition, and both versions checked to agree on every year.',
    difficulty: 'Easy',
    source: LoopScripts.LeapYearChecker,
  },
  {
    id: 'loops-weekly-expenses',
    title: 'Accumulator: Weekly Expenses',
    category: 'Loops & Control',
    description: 'A running total and an over-budget counter grow inside the loop; the average and the weekly verdict are computed after it.',
    difficulty: 'Easy',
    source: LoopScripts.WeeklyExpenses,
  },
  {
    id: 'loops-hottest-coldest',
    title: 'Best So Far: Hottest & Coldest Day',
    category: 'Loops & Control',
    description: 'Start from day 1 as both records and let every later day challenge them with COMPARE and IF: the hottest, the coldest and the range, in one pass.',
    difficulty: 'Easy',
    source: LoopScripts.HottestAndColdestDay,
  },
  {
    id: 'loops-second-largest',
    title: 'Second Largest in One Pass',
    category: 'Loops & Control',
    description: 'An IF / ELSE IF chain with AND keeps the largest and the second largest different score in one loop, handling repeated values.',
    difficulty: 'Medium',
    source: LoopScripts.SecondLargest,
  },
  {
    id: 'loops-stopping-early',
    title: 'Stopping Early (break with a flag)',
    category: 'Loops & Control',
    description: 'There is no BREAK: a found flag in the WHILE condition stops a roll-number search at the match, and a missing roll checks every entry.',
    difficulty: 'Easy',
    source: LoopScripts.StoppingEarly,
  },
  {
    id: 'loops-skipping-items',
    title: 'Skipping Items (continue with IF / ELSE)',
    category: 'Loops & Control',
    description: 'There is no CONTINUE: offline (-1) and glitched (999) sensor readings are skipped by an IF branch, and the average uses only valid readings, guarded against dividing by 0.',
    difficulty: 'Easy',
    source: LoopScripts.SkippingInvalidReadings,
  },
  {
    id: 'loops-do-while-atm',
    title: 'Do-While: PIN Attempts & ATM',
    category: 'Loops & Control',
    description: 'A do-while built from WHILE and a flag gives at most 3 PIN tries (the body always runs once), then a WHILE over withdrawals declines requests larger than the balance.',
    difficulty: 'Medium',
    source: LoopScripts.DoWhilePinAndAtm,
  },
  {
    id: 'loops-fizzbuzz',
    title: 'FizzBuzz',
    category: 'Loops & Control',
    description: 'The classic % exercise, and why the "divisible by both" test must come first in the ELSE IF chain.',
    difficulty: 'Easy',
    source: LoopScripts.FizzBuzz,
  },
  {
    id: 'loops-multiplication-table',
    title: 'Nested Loops: Multiplication Table',
    category: 'Loops & Control',
    description: 'The inner loop fills a whole row for every round of the outer loop: tables 1 to 5, aligned columns, 25 inner rounds and the sum of the table.',
    difficulty: 'Easy',
    source: LoopScripts.MultiplicationTable,
  },
  {
    id: 'loops-star-patterns',
    title: 'Nested Loops: Star & Number Patterns',
    category: 'Loops & Control',
    description: 'Right triangle, centred pyramid and Floyd\'s triangle built character by character, with a WHILE for the spaces because LOOP 1 TO 0 would run twice.',
    difficulty: 'Medium',
    source: LoopScripts.StarPatterns,
  },
  {
    id: 'loops-gift-pairs',
    title: 'All Pairs: Gifts Within Budget',
    category: 'Loops & Control',
    description: 'Two nested loops with j starting at i + 1 check every pair of different gifts once (15 checks for 6 gifts) and find the pairs that cost exactly the budget.',
    difficulty: 'Medium',
    source: LoopScripts.GiftPairsWithinBudget,
  },
  {
    id: 'loops-counting-vowels',
    title: 'Counting Vowels in a Sentence',
    category: 'Loops & Control',
    description: 'Loop over text with TEXT_LENGTH, CHAR_AT and CHAR_CODE: vowels, consonants, spaces and words, counted in an array that updates live.',
    difficulty: 'Easy',
    source: LoopScripts.CountingVowels,
  },
  {
    id: 'loops-fibonacci',
    title: 'Fibonacci Series',
    category: 'Loops & Control',
    description: 'A LOOP builds the first 12 Fibonacci numbers from the two before each one, a second loop counts the even ones, and a WHILE finds the first one above 1000.',
    difficulty: 'Easy',
    source: LoopScripts.FibonacciSeries,
  },
  {
    id: 'loops-prime-check',
    title: 'Prime Check with Early RETURN',
    category: 'Loops & Control',
    description: 'An isPrime FUNCTION tries divisors only while d * d <= n and RETURNs the moment it finds one, showing the factor pair of every non-prime.',
    difficulty: 'Medium',
    source: LoopScripts.PrimeCheck,
  },
  {
    id: 'loops-sieve',
    title: 'Sieve of Eratosthenes',
    category: 'Loops & Control',
    description: 'Every prime up to 30 without a single division: each prime crosses out its multiples from p * p with a WHILE loop inside a LOOP.',
    difficulty: 'Medium',
    source: LoopScripts.SieveOfEratosthenes,
  },
  {
    id: 'loops-gcd-lcm',
    title: "Euclid's GCD & LCM",
    category: 'Loops & Control',
    description: 'A WHILE loop replaces (a, b) with (b, a % b) until b is 0, the LCM follows from the GCD, and the older subtraction version needs twice the steps.',
    difficulty: 'Medium',
    source: LoopScripts.EuclidGcdLcm,
  },
  {
    id: 'loops-decimal-to-binary',
    title: 'Decimal to Binary and Back',
    category: 'Loops & Control',
    description: 'Divide by 2 in a WHILE loop, inserting each remainder bit at the front, then convert back by doubling and adding to check the round trip.',
    difficulty: 'Medium',
    source: LoopScripts.DecimalToBinary,
  },
  {
    id: 'loops-palindrome-armstrong',
    title: 'Palindrome & Armstrong Numbers',
    category: 'Loops & Control',
    description: 'Helper FUNCTIONs with loops inside (countDigits, power, reverseNumber, isArmstrong) classify each number, combined with an IF / ELSE IF chain.',
    difficulty: 'Medium',
    source: LoopScripts.PalindromeAndArmstrong,
  },
  {
    id: 'loops-collatz',
    title: 'Collatz Sequence (3n + 1)',
    category: 'Loops & Control',
    description: 'A WHILE loop that cannot know its length in advance traces 6 down to 1, then a WHILE inside a LOOP finds which start from 1 to 10 takes the longest.',
    difficulty: 'Hard',
    source: LoopScripts.CollatzSequence,
  },

  // ── Stacks ────────────────────────────────────────────────────────────────────
  {
    id: 'stacks-foundation',
    title: 'Stack Foundation',
    category: 'Stacks',
    description: 'PUSH, POP, PEEK, LENGTH and IS_EMPTY in a loop: values come back out in last-in-first-out order, and a safe pop checks for underflow first.',
    difficulty: 'Easy',
    source: StackScripts.StackFoundation,
  },
  {
    id: 'stacks-using-array',
    title: 'Stack Using an Array',
    category: 'Stacks',
    description: 'How a stack is really built: a fixed-size array plus a top index, with explicit STACK OVERFLOW and STACK UNDERFLOW checks.',
    difficulty: 'Easy',
    source: StackScripts.StackUsingArray,
  },
  {
    id: 'stacks-reverse-array',
    title: 'Reverse an Array',
    category: 'Stacks',
    description: 'Push every element, then pop them back into the array from index 0 — the array ends up reversed in place.',
    difficulty: 'Easy',
    source: StackScripts.ReverseArrayWithStack,
  },
  {
    id: 'stacks-reverse-string',
    title: 'Reverse a String',
    category: 'Stacks',
    description: 'Push each character of a word, then pop them one by one to build the word backwards.',
    difficulty: 'Easy',
    source: StackScripts.ReverseStringWithStack,
  },
  {
    id: 'stacks-palindrome',
    title: 'Palindrome Check',
    category: 'Stacks',
    description: 'Popping reads a word backwards: compare each popped character with the word read forwards, stopping at the first mismatch.',
    difficulty: 'Easy',
    source: StackScripts.PalindromeCheck,
  },
  {
    id: 'stacks-balanced-parens',
    title: 'Balanced Parentheses',
    category: 'Stacks',
    description: 'Push every opening bracket; every closing bracket must match the top. Detects mismatches, stray closers and unclosed brackets.',
    difficulty: 'Medium',
    source: StackScripts.BalancedParentheses,
  },
  {
    id: 'stacks-postfix-evaluation',
    title: 'Evaluate Postfix Expression',
    category: 'Stacks',
    description: 'A calculator’s stack: push numbers, and on each operator pop two operands, compute, and push the result. Rejects invalid expressions.',
    difficulty: 'Medium',
    source: StackScripts.EvaluatePostfixExpression,
  },
  {
    id: 'stacks-infix-to-postfix',
    title: 'Infix to Postfix',
    category: 'Stacks',
    description: 'The Shunting-Yard algorithm: an operator stack plus a precedence function turns A * ( B + C ) - D / E into A B C + * D E / -.',
    difficulty: 'Hard',
    source: StackScripts.InfixToPostfix,
  },
  {
    id: 'stacks-next-greater-element',
    title: 'Next Greater Element',
    category: 'Stacks',
    description: 'The monotonic-stack pattern: a stack of waiting indexes answers every element’s next greater value in O(n).',
    difficulty: 'Hard',
    source: StackScripts.NextGreaterElement,
  },
  {
    id: 'stacks-stock-span',
    title: 'Stock Span',
    category: 'Stacks',
    description: 'For each day, how many consecutive days had a price no higher than today — computed with a stack of higher-price days.',
    difficulty: 'Hard',
    source: StackScripts.StockSpan,
  },
  {
    id: 'stacks-min-stack',
    title: 'Min Stack',
    category: 'Stacks',
    description: 'A second stack keeps the current minimum on its top, so the minimum is known in O(1) after every push and pop.',
    difficulty: 'Medium',
    source: StackScripts.MinStack,
  },
  {
    id: 'stacks-sort-stack',
    title: 'Sort a Stack',
    category: 'Stacks',
    description: 'Sort using only one extra stack: bigger values are moved back out of the way so the sorted stack stays in order.',
    difficulty: 'Medium',
    source: StackScripts.SortStack,
  },
  {
    id: 'stacks-decimal-to-binary',
    title: 'Decimal to Binary',
    category: 'Stacks',
    description: 'Repeated division by 2 gives the digits last-first; a stack puts them back in the right order. Works for any base 2–10.',
    difficulty: 'Easy',
    source: StackScripts.DecimalToBinary,
  },
  {
    id: 'stacks-undo-redo',
    title: 'Undo / Redo',
    category: 'Stacks',
    description: 'How a text editor’s Undo and Redo buttons work: two stacks, and a new edit clears the redo history.',
    difficulty: 'Medium',
    source: StackScripts.UndoRedo,
  },
  {
    id: 'stacks-factorial',
    title: 'Recursion as a Stack',
    category: 'Stacks',
    description: 'Factorial computed the way the call stack does it: push the waiting calls, then pop them and multiply as each one returns.',
    difficulty: 'Medium',
    source: StackScripts.FactorialWithStack,
  },

  // ── Queues ────────────────────────────────────────────────────────────────────
  {
    id: 'queues-foundation',
    title: 'Queue Foundation',
    category: 'Queues',
    description: 'FIFO in action: enqueue a batch at the rear, read FRONT and REAR, dequeue until empty, and guard against QUEUE UNDERFLOW with IS_EMPTY.',
    difficulty: 'Easy',
    source: QueueScripts.QueueFoundation,
  },
  {
    id: 'queues-using-array',
    title: 'Queue Using an Array',
    category: 'Queues',
    description: 'How a linear queue is really built: a fixed array with front and rear indexes, explicit OVERFLOW / UNDERFLOW checks — and the wasted slots it leaves behind.',
    difficulty: 'Easy',
    source: QueueScripts.QueueUsingArray,
  },
  {
    id: 'queues-circular',
    title: 'Circular Queue',
    category: 'Queues',
    description: 'The fix for the linear queue: front and rear wrap around with (index + 1) % capacity, so freed slots are reused.',
    difficulty: 'Medium',
    source: QueueScripts.CircularQueue,
  },
  {
    id: 'queues-bank-teller',
    title: 'Bank Teller Simulation',
    category: 'Queues',
    description: 'Customers arrive minute by minute and wait in line for one teller; computes every customer’s waiting time and the average.',
    difficulty: 'Medium',
    source: QueueScripts.BankTellerSimulation,
  },
  {
    id: 'queues-round-robin',
    title: 'Round Robin CPU Scheduling',
    category: 'Queues',
    description: 'An operating system’s ready queue: each process runs for one time quantum and goes back to the rear until done. Computes completion and waiting times.',
    difficulty: 'Medium',
    source: QueueScripts.RoundRobinScheduling,
  },
  {
    id: 'queues-generate-binary',
    title: 'Generate Binary Numbers',
    category: 'Queues',
    description: 'Dequeue a number, enqueue it with "0" and "1" appended: the queue produces 1, 10, 11, 100, … in increasing order.',
    difficulty: 'Easy',
    source: QueueScripts.GenerateBinaryNumbers,
  },
  {
    id: 'queues-reverse-with-stack',
    title: 'Reverse a Queue',
    category: 'Queues',
    description: 'FIFO in, LIFO out: draining a queue through a stack and back reverses its order.',
    difficulty: 'Easy',
    source: QueueScripts.ReverseQueueWithStack,
  },
  {
    id: 'queues-reverse-first-k',
    title: 'Reverse the First K Elements',
    category: 'Queues',
    description: 'Reverse only the first k elements with a stack, then rotate the rest behind them. Rejects an invalid k.',
    difficulty: 'Medium',
    source: QueueScripts.ReverseFirstK,
  },
  {
    id: 'queues-interleave',
    title: 'Interleave Two Halves',
    category: 'Queues',
    description: 'Shuffle like a deck of cards: move the first half to a second queue, then take one element from each in turn.',
    difficulty: 'Medium',
    source: QueueScripts.InterleaveHalves,
  },
  {
    id: 'queues-using-two-stacks',
    title: 'Queue Using Two Stacks',
    category: 'Queues',
    description: 'A FIFO queue from two LIFO stacks, driven by a list of operations: the outbox is refilled from the inbox only when it runs dry.',
    difficulty: 'Hard',
    source: QueueScripts.QueueUsingTwoStacks,
  },
  {
    id: 'queues-hot-potato',
    title: 'Hot Potato (Josephus)',
    category: 'Queues',
    description: 'Players in a circle pass a potato: rotate the queue k times and eliminate whoever holds it, until one winner is left.',
    difficulty: 'Medium',
    source: QueueScripts.HotPotato,
  },
  {
    id: 'queues-moving-average',
    title: 'Moving Average of a Sensor',
    category: 'Queues',
    description: 'A sliding window of the last k readings: enqueue the newest, dequeue the oldest, and keep a running sum for O(1) averages.',
    difficulty: 'Medium',
    source: QueueScripts.MovingAverage,
  },
  {
    id: 'queues-first-non-repeating',
    title: 'First Non-Repeating Character',
    category: 'Queues',
    description: 'For a stream of characters, report the first one seen only once after every arrival; repeated candidates leave the queue’s front.',
    difficulty: 'Hard',
    source: QueueScripts.FirstNonRepeating,
  },

  // ── Graphs ────────────────────────────────────────────────────────────────────
  {
    id: 'graphs-basics',
    title: 'Graph Basics: Friends Network',
    category: 'Graphs',
    description: 'Vertices, edges and adjacency lists. Loop over every person with VERTEX_AT and over their friends with NEIGHBOR, find the most connected one, test HAS_EDGE, then change the graph with ADD_EDGE / ADD_VERTEX / REMOVE_EDGE and check the handshake lemma.',
    difficulty: 'Easy',
    source: GraphScripts.GraphBasics,
  },
  {
    id: 'graphs-directed-weighted',
    title: 'Directed & Weighted: Flight Routes',
    category: 'Graphs',
    description: 'One-way flights with durations as edge weights: departures per airport, in-degree vs out-degree, the busiest airport, why HAS_EDGE depends on direction, and a walk over the edge list with EDGE_AT.',
    difficulty: 'Easy',
    source: GraphScripts.DirectedWeighted,
  },
  {
    id: 'graphs-adjacency-matrix',
    title: 'Adjacency Matrix vs List',
    category: 'Graphs',
    description: 'Build the V x V adjacency matrix of a graph row by row with two nested loops and HAS_EDGE, and compare its size with the adjacency list.',
    difficulty: 'Easy',
    source: GraphScripts.AdjacencyMatrix,
  },
  {
    id: 'graphs-bfs',
    title: 'Breadth-First Search: Degrees of Separation',
    category: 'Graphs',
    description: 'BFS with a real queue of vertices and visited marks. Every person gets a dist (steps from the start) and a parent, the network is printed ring by ring, and unreachable people are reported.',
    difficulty: 'Medium',
    source: GraphScripts.BreadthFirstSearch,
  },
  {
    id: 'graphs-bfs-shortest-path',
    title: 'Fewest Metro Stops (BFS Path)',
    category: 'Graphs',
    description: 'BFS stops as soon as it reaches the goal station; the route is rebuilt by following parent fields back and reversed with a stack.',
    difficulty: 'Medium',
    source: GraphScripts.ShortestPathBFS,
  },
  {
    id: 'graphs-dfs',
    title: 'Depth-First Search: Maze Explorer',
    category: 'Graphs',
    description: 'Iterative DFS with an explicit stack: rooms are explored one corridor at a time, neighbours pushed in reverse so they are visited in list order.',
    difficulty: 'Medium',
    source: GraphScripts.DepthFirstSearch,
  },
  {
    id: 'graphs-dfs-recursive',
    title: 'Recursive DFS: Web Crawler',
    category: 'Graphs',
    description: 'A recursive crawl over a directed graph of web pages. Every call and return is a step, waiting calls show in purple, the function RETURNS how many pages it found, and orphan pages are detected.',
    difficulty: 'Medium',
    source: GraphScripts.RecursiveDFS,
  },
  {
    id: 'graphs-components',
    title: 'Connected Components: Office LAN',
    category: 'Graphs',
    description: 'Loop over all vertices and start a stack-based DFS from each unvisited one; every network of computers gets its own group number and colour.',
    difficulty: 'Medium',
    source: GraphScripts.ConnectedComponents,
  },
  {
    id: 'graphs-cycle-undirected',
    title: 'Cycle Detection (Undirected)',
    category: 'Graphs',
    description: 'A recursive DFS that remembers where it came from finds a loop in a pipe network — first none (the network is a tree with V - 1 edges), then one after ADD_EDGE.',
    difficulty: 'Medium',
    source: GraphScripts.UndirectedCycle,
  },
  {
    id: 'graphs-cycle-directed',
    title: 'Cycle Detection (Directed): Course Prerequisites',
    category: 'Graphs',
    description: 'WHITE / GRAY / BLACK colouring with recursion finds a circular prerequisite chain and prints the exact cycle by following parent fields.',
    difficulty: 'Hard',
    source: GraphScripts.DirectedCycle,
  },
  {
    id: 'graphs-bipartite',
    title: 'Bipartite Check: Two Teams',
    category: 'Graphs',
    description: 'BFS 2-colouring splits rivals into two teams; after a new rivalry forms a triangle (an odd cycle) the same function reports the conflict.',
    difficulty: 'Hard',
    source: GraphScripts.BipartiteCheck,
  },
  {
    id: 'graphs-topo-kahn',
    title: 'Topological Sort (Kahn\'s): Course Schedule',
    category: 'Graphs',
    description: 'Kahn\'s algorithm with IN_DEGREE counts and a queue of courses whose prerequisites are all done; also checks for a cycle.',
    difficulty: 'Medium',
    source: GraphScripts.TopologicalSortKahn,
  },
  {
    id: 'graphs-topo-dfs',
    title: 'Topological Sort (DFS): Getting Dressed',
    category: 'Graphs',
    description: 'Recursive DFS pushes each item on a stack when it finishes; popping the stack gives a valid dressing order.',
    difficulty: 'Medium',
    source: GraphScripts.TopologicalSortDFS,
  },
  {
    id: 'graphs-dijkstra',
    title: 'Dijkstra\'s Shortest Path: Delivery Route',
    category: 'Graphs',
    description: 'Dijkstra\'s algorithm written out: dist = INFINITY, a loop that picks the closest unfinished place, edge relaxation with WEIGHT, and the route rebuilt from parent fields.',
    difficulty: 'Hard',
    source: GraphScripts.DijkstraShortestPath,
  },
  {
    id: 'graphs-bellman-ford',
    title: 'Bellman-Ford: Drone Battery (Negative Weights)',
    category: 'Graphs',
    description: 'Relax every edge (EDGE_AT) in rounds and watch the distances improve, with a negative-weight edge; an extra round checks for a negative cycle.',
    difficulty: 'Hard',
    source: GraphScripts.BellmanFordAlgorithm,
  },
  {
    id: 'graphs-prim',
    title: 'Prim\'s MST: Fibre Between Offices',
    category: 'Graphs',
    description: 'Prim\'s algorithm with key and parent fields grows the minimum spanning tree from one office; tree edges turn green as they are chosen.',
    difficulty: 'Hard',
    source: GraphScripts.PrimsMST,
  },
  {
    id: 'graphs-kruskal',
    title: 'Kruskal\'s MST: Village Roads',
    category: 'Graphs',
    description: 'Kruskal\'s algorithm takes roads cheapest-first and uses union-find (leader pointers and a findLeader function) to reject roads that would close a cycle.',
    difficulty: 'Hard',
    source: GraphScripts.KruskalsMST,
  },
  {
    id: 'graphs-all-paths',
    title: 'All Routes: Backtracking',
    category: 'Graphs',
    description: 'A recursive search lists every route from Home to School without revisiting a place, marking and un-marking vertices as it backtracks.',
    difficulty: 'Hard',
    source: GraphScripts.CountAllPaths,
  },
  {
    id: 'graphs-coloring',
    title: 'Greedy Colouring: Exam Timetable',
    category: 'Graphs',
    description: 'Give each exam the lowest time slot none of its conflicting exams uses; each slot is painted its own colour.',
    difficulty: 'Medium',
    source: GraphScripts.GreedyColoring,
  },

  // ── Heaps ─────────────────────────────────────────────────────────────────────
  // Every example is the real algorithm (loops, IFs, FUNCTIONs over h[i]), not a built-in.
  {
    id: 'heaps-index-map',
    title: 'Heap Index Map',
    category: 'Heaps',
    description: 'Walk every index of a heap and work out its parent and children from 2i + 1, 2i + 2 and (i - 1) / 2 rounded down: no pointers needed.',
    difficulty: 'Easy',
    source: HeapScripts.HeapIndexMap,
  },
  {
    id: 'heaps-is-valid',
    title: 'Is It a Min-Heap?',
    category: 'Heaps',
    description: 'Check every parent against its children with a LOOP and IFs, marking each pair that breaks the min-heap rule.',
    difficulty: 'Easy',
    source: HeapScripts.IsValidMinHeap,
  },
  {
    id: 'heaps-insert',
    title: 'Insert and Sift Up',
    category: 'Heaps',
    description: 'Add each arriving value as the new last cell, then a siftUp FUNCTION swaps it with its parent while it is smaller.',
    difficulty: 'Medium',
    source: HeapScripts.MinHeapInsert,
  },
  {
    id: 'heaps-extract-min',
    title: 'Extract Minimum',
    category: 'Heaps',
    description: 'An extractMin FUNCTION moves the last value onto the root, deletes the last cell and sifts the root down, returning the smallest value.',
    difficulty: 'Medium',
    source: HeapScripts.ExtractMin,
  },
  {
    id: 'heaps-max-heap-auction',
    title: 'Max-Heap: Auction Bids',
    category: 'Heaps',
    description: 'The same sift code with the comparisons flipped keeps the highest bid on top; three items are sold to the highest remaining bids.',
    difficulty: 'Medium',
    source: HeapScripts.MaxHeapAuction,
  },
  {
    id: 'heaps-build-bottom-up',
    title: 'Build Heap Bottom-Up (Floyd)',
    category: 'Heaps',
    description: 'Turn an unordered array into a min-heap in O(n) by sifting down every parent from the last one back to the root, counting the swaps.',
    difficulty: 'Medium',
    source: HeapScripts.BuildHeapBottomUp,
  },
  {
    id: 'heaps-heapify-recursive',
    title: 'Heapify (Recursive)',
    category: 'Heaps',
    description: 'A recursive heapify FUNCTION fixes one broken node, then calls itself on the child that received the bigger value.',
    difficulty: 'Medium',
    source: HeapScripts.HeapifyRecursive,
  },
  {
    id: 'heaps-decrease-key',
    title: 'Decrease Key',
    category: 'Heaps',
    description: 'Lower a distance in place and sift it up, as Dijkstra\'s algorithm does; an increase is rejected with a message.',
    difficulty: 'Medium',
    source: HeapScripts.DecreaseKey,
  },
  {
    id: 'heaps-delete-at-index',
    title: 'Delete at Any Index',
    category: 'Heaps',
    description: 'Fill the hole with the last value, then decide with IFs whether it must sift up or sift down; both cases are shown.',
    difficulty: 'Hard',
    source: HeapScripts.DeleteAtIndex,
  },
  {
    id: 'heaps-heap-sort',
    title: 'Heap Sort (In Place)',
    category: 'Heaps',
    description: 'Build a max-heap, then repeatedly swap the root to the end of the unsorted part and repair the shrunken heap.',
    difficulty: 'Hard',
    source: HeapScripts.HeapSortInPlace,
  },
  {
    id: 'heaps-emergency-room',
    title: 'Emergency Room Triage',
    category: 'Heaps',
    description: 'A max-heap priority queue of severities with a parallel array of patient names: the most urgent patient is always seen first.',
    difficulty: 'Medium',
    source: HeapScripts.EmergencyRoom,
  },
  {
    id: 'heaps-top-k-scores',
    title: 'Top K Scores',
    category: 'Heaps',
    description: 'Keep a min-heap of the best k scores seen so far; a new score gets in only if it beats the root. O(n log k).',
    difficulty: 'Medium',
    source: HeapScripts.TopKScores,
  },
  {
    id: 'heaps-kth-smallest',
    title: 'Kth Smallest Delivery Time',
    category: 'Heaps',
    description: 'Put every delivery time in a min-heap and remove the root k - 1 times: the root is then the k-th smallest.',
    difficulty: 'Easy',
    source: HeapScripts.KthSmallest,
  },
  {
    id: 'heaps-connect-ropes',
    title: 'Connect Ropes at Minimum Cost',
    category: 'Heaps',
    description: 'Greedy with a min-heap: always join the two shortest ropes and put the joined rope back, adding up the cost.',
    difficulty: 'Medium',
    source: HeapScripts.ConnectRopes,
  },
  {
    id: 'heaps-last-stone',
    title: 'Last Stone Weight',
    category: 'Heaps',
    description: 'Smash the two heaviest stones taken from a max-heap; if they differ, the leftover stone goes back into the heap.',
    difficulty: 'Easy',
    source: HeapScripts.LastStoneWeight,
  },
  {
    id: 'heaps-running-median',
    title: 'Running Median (Two Heaps)',
    category: 'Heaps',
    description: 'A max-heap for the smaller half and a min-heap for the bigger half give the median after every new number.',
    difficulty: 'Hard',
    source: HeapScripts.RunningMedian,
  },

  // ── Hash Maps ─────────────────────────────────────────────────────────────────
  {
    id: 'hashmaps-hash-function',
    title: 'Hash Function by Hand',
    category: 'Hash Maps',
    description: 'A hashOf FUNCTION adds up character codes in a LOOP and takes the remainder, matches BUCKET_OF, and spots collisions: anagrams always share a bucket.',
    difficulty: 'Easy',
    source: HashMapScripts.HashFunctionByHand,
  },
  {
    id: 'hashmaps-phone-book',
    title: 'Phone Book: Store, Update, Look Up, Delete',
    category: 'Hash Maps',
    description: 'The four basic moves: m[key] = value adds or overwrites, CONTAINS guards every read of a key that may be missing, DELETE removes a contact.',
    difficulty: 'Easy',
    source: HashMapScripts.PhoneBook,
  },
  {
    id: 'hashmaps-collisions',
    title: 'Collisions and Chaining',
    category: 'Hash Maps',
    description: 'Locker numbers that leave the same remainder pile up in one bucket\'s chain; a FUNCTION counts how many comparisons each lookup needs.',
    difficulty: 'Easy',
    source: HashMapScripts.CollisionsAndChaining,
  },
  {
    id: 'hashmaps-load-factor',
    title: 'Load Factor and Resizing',
    category: 'Hash Maps',
    description: 'Watch size / capacity after every insert: past 0.75 the bucket row doubles (8, 16, 32) and every key is rehashed into its new bucket.',
    difficulty: 'Medium',
    source: HashMapScripts.LoadFactorAndResize,
  },
  {
    id: 'hashmaps-shopping-cart',
    title: 'Shopping Cart Totals',
    category: 'Hash Maps',
    description: 'Two maps (price list and cart): add quantities with IF CONTAINS / ELSE, then walk every key with KEY_AT to total the bill and apply a discount.',
    difficulty: 'Easy',
    source: HashMapScripts.ShoppingCartTotals,
  },
  {
    id: 'hashmaps-open-addressing',
    title: 'Open Addressing by Hand',
    category: 'Hash Maps',
    description: 'A hash table built from two plain arrays with linear probing: insert and search FUNCTIONs step to the next slot until they find a free one or the key.',
    difficulty: 'Medium',
    source: HashMapScripts.OpenAddressingByHand,
  },
  {
    id: 'hashmaps-word-frequency',
    title: 'Word Frequency Counter',
    category: 'Hash Maps',
    description: 'Split a sentence into words with CHAR_AT, count each word in a map through a countWord FUNCTION, then find the most frequent word.',
    difficulty: 'Easy',
    source: HashMapScripts.WordFrequencyCounter,
  },
  {
    id: 'hashmaps-first-unique',
    title: 'First Non-Repeating Character',
    category: 'Hash Maps',
    description: 'Pass 1 counts every character in a map; pass 2 walks the text in order and stops at the first character counted once.',
    difficulty: 'Easy',
    source: HashMapScripts.FirstUniqueCharacter,
  },
  {
    id: 'hashmaps-valid-anagram',
    title: 'Valid Anagram',
    category: 'Hash Maps',
    description: 'An isAnagram FUNCTION adds 1 for each letter of one word and subtracts 1 for the other; anagrams leave every letter at 0.',
    difficulty: 'Easy',
    source: HashMapScripts.ValidAnagram,
  },
  {
    id: 'hashmaps-two-sum',
    title: 'Two Sum in One Pass',
    category: 'Hash Maps',
    description: 'For each number, look up the partner it needs (target - number) among the numbers already seen: O(n) instead of trying every pair.',
    difficulty: 'Easy',
    source: HashMapScripts.TwoSum,
  },
  {
    id: 'hashmaps-first-duplicate',
    title: 'First Reused Ticket',
    category: 'Hash Maps',
    description: 'A stadium gate remembers where each ticket was first scanned and stops at the first ticket scanned twice.',
    difficulty: 'Easy',
    source: HashMapScripts.FirstDuplicate,
  },
  {
    id: 'hashmaps-longest-consecutive',
    title: 'Longest Consecutive Run',
    category: 'Hash Maps',
    description: 'Store every number in a map used as a set, then count up only from numbers whose predecessor is missing: O(n) without sorting.',
    difficulty: 'Medium',
    source: HashMapScripts.LongestConsecutiveRun,
  },
  {
    id: 'hashmaps-subarray-sum',
    title: 'Subarrays That Add Up to K',
    category: 'Hash Maps',
    description: 'Count how often each running (prefix) sum has appeared; every earlier prefix equal to sum - k closes one subarray adding up to k.',
    difficulty: 'Hard',
    source: HashMapScripts.SubarraySumEqualsK,
  },
  {
    id: 'hashmaps-longest-substring',
    title: 'Longest Substring Without Repeats',
    category: 'Hash Maps',
    description: 'A sliding window with a map of where each letter was last seen: a repeat inside the window moves the window\'s start past it.',
    difficulty: 'Medium',
    source: HashMapScripts.LongestSubstringWithoutRepeats,
  },
  {
    id: 'hashmaps-election',
    title: 'Election Tally',
    category: 'Hash Maps',
    description: 'Count ballots per candidate, then walk the map to find the winner, with a separate branch for a tie.',
    difficulty: 'Easy',
    source: HashMapScripts.ElectionTally,
  },
  {
    id: 'hashmaps-ransom-note',
    title: 'Ransom Note',
    category: 'Hash Maps',
    description: 'Count the letters a magazine offers, then spend them one by one on the note, stopping at the first letter that runs out.',
    difficulty: 'Easy',
    source: HashMapScripts.RansomNote,
  },
  {
    id: 'hashmaps-memo-fibonacci',
    title: 'Memoized Fibonacci',
    category: 'Hash Maps',
    description: 'A recursive fib FUNCTION remembers every answer in a map, so each fib(n) is computed once and asked again in a single lookup.',
    difficulty: 'Medium',
    source: HashMapScripts.MemoizedFibonacci,
  },

  // ── Tries ─────────────────────────────────────────────────────────────────────
  {
    id: 'tries-insert-by-hand',
    title: 'Insert Words by Hand',
    category: 'Tries',
    description: 'An insertWord FUNCTION walks the word letter by letter: HAS_CHILD decides whether ADD_CHILD must create the node, GET_CHILD steps down, isEnd marks the last letter. Counts the nodes shared prefixes save.',
    difficulty: 'Easy',
    source: TrieScripts.InsertWordsByHand,
  },
  {
    id: 'tries-search-word',
    title: 'Search for a Whole Word',
    category: 'Tries',
    description: 'A search FUNCTION follows one edge per letter and stops at the first NULL; only a node marked isEnd holds a word, so the prefix "ca" is not found.',
    difficulty: 'Easy',
    source: TrieScripts.SearchWholeWord,
  },
  {
    id: 'tries-starts-with',
    title: 'Starts With a Prefix',
    category: 'Tries',
    description: 'The same walk without the final isEnd test answers "does any word start with this?" — side by side with the whole-word check.',
    difficulty: 'Easy',
    source: TrieScripts.StartsWithPrefix,
  },
  {
    id: 'tries-count-words-nodes',
    title: 'Count Words, Nodes and Leaves',
    category: 'Tries',
    description: 'Recursive FUNCTIONs visit every node once (children with CHILD_AT in a WHILE loop) to count words, nodes, leaves and the longest word, checked against WORD_COUNT and NODE_COUNT.',
    difficulty: 'Medium',
    source: TrieScripts.CountWordsAndNodes,
  },
  {
    id: 'tries-dictionary-order',
    title: 'Trie Sort: Dictionary Order',
    category: 'Tries',
    description: 'Insert unsorted words, then a depth-first walk that visits children a to z and builds the prefix as it goes writes them out sorted.',
    difficulty: 'Medium',
    source: TrieScripts.DictionaryInOrder,
  },
  {
    id: 'tries-autocomplete',
    title: 'Autocomplete Suggestions',
    category: 'Tries',
    description: 'Walk down to the node of the typed prefix, then collect at most 4 words below it depth-first — only that subtree is ever visited.',
    difficulty: 'Medium',
    source: TrieScripts.AutocompleteSuggestions,
  },
  {
    id: 'tries-delete-word',
    title: 'Delete a Word with Pruning',
    category: 'Tries',
    description: 'A recursive removeWord unmarks the end of the word, and on the way back up REMOVE_CHILD unlinks every node no other word needs.',
    difficulty: 'Hard',
    source: TrieScripts.DeleteWordWithPruning,
  },
  {
    id: 'tries-prefix-counter',
    title: 'Count Names by Prefix',
    category: 'Tries',
    description: 'Every node stores a count of the words passing through it, so "how many usernames start with sa?" is one walk down the prefix.',
    difficulty: 'Medium',
    source: TrieScripts.PrefixCounter,
  },
  {
    id: 'tries-word-frequency',
    title: 'Word Frequency Counter',
    category: 'Tries',
    description: 'Split a sentence by hand, store how often each word appears in the node where it ends, then report every word a to z with its count.',
    difficulty: 'Medium',
    source: TrieScripts.WordFrequencyCounter,
  },
  {
    id: 'tries-longest-common-prefix',
    title: 'Longest Common Prefix',
    category: 'Tries',
    description: 'Insert all words, then walk down from the root while exactly one child continues and no word ends — the path is the common prefix.',
    difficulty: 'Easy',
    source: TrieScripts.LongestCommonPrefix,
  },
  {
    id: 'tries-shortest-unique-prefix',
    title: 'Shortest Unique Prefix',
    category: 'Tries',
    description: 'With a pass-through count on every node, the shortest unambiguous abbreviation ends at the first node only that word uses.',
    difficulty: 'Medium',
    source: TrieScripts.ShortestUniquePrefix,
  },
  {
    id: 'tries-replace-with-roots',
    title: 'Replace Words with Their Roots',
    category: 'Tries',
    description: 'Each word of a sentence is replaced by the shortest dictionary root it starts with, found by stopping at the first isEnd on its path.',
    difficulty: 'Medium',
    source: TrieScripts.ReplaceWordsWithRoots,
  },
  {
    id: 'tries-word-break',
    title: 'Word Break',
    category: 'Tries',
    description: 'Can a text be split into dictionary words? From every reachable position a trie walk marks where each word ends, stopping as soon as no word continues.',
    difficulty: 'Hard',
    source: TrieScripts.WordBreak,
  },
  {
    id: 'tries-longest-built-word',
    title: 'Longest Word Built Step by Step',
    category: 'Tries',
    description: 'A recursive search that only follows word-ending children finds the longest word whose every prefix is also a word (ties: alphabetically first).',
    difficulty: 'Medium',
    source: TrieScripts.LongestWordBuiltStepByStep,
  },
  {
    id: 'tries-distinct-substrings',
    title: 'Count Distinct Substrings',
    category: 'Tries',
    description: 'Put every suffix of "banana" into a trie: each node is one different substring, so 15 nodes means 15 distinct substrings.',
    difficulty: 'Hard',
    source: TrieScripts.CountDistinctSubstrings,
  },
  {
    id: 'tries-wildcard-search',
    title: 'Wildcard Search with "."',
    category: 'Tries',
    description: 'A recursive matches FUNCTION follows one edge for a letter but tries every child for a ".", like a word-puzzle solver.',
    difficulty: 'Hard',
    source: TrieScripts.WildcardSearch,
  },
  {
    id: 'tries-search-as-you-type',
    title: 'Contact Search as You Type',
    category: 'Tries',
    description: 'Keep the node of what has been typed and take one step per new letter instead of restarting from the root, listing the matches each time.',
    difficulty: 'Medium',
    source: TrieScripts.ContactSearchAsYouType,
  },
  {
    id: 'tries-maximum-xor',
    title: 'Maximum XOR of Two Numbers',
    category: 'Tries',
    description: 'Numbers become paths of 0 / 1 edges (bits worked out by hand); at every bit the walk takes the opposite bit when it exists, giving the largest XOR.',
    difficulty: 'Hard',
    source: TrieScripts.MaximumXorPair,
  },

  // ── Recursion & Functions ─────────────────────────────────────────────────────
  // Every example is real code: FUNCTIONs with parameters and RETURN, guard
  // clauses, IF / ELSE IF ladders, loops and recursion with a base case.
  {
    id: 'fn-basics',
    title: 'Functions: Canteen Bill',
    category: 'Recursion & Functions',
    description: 'lineTotal, discountOn, gstOn and finalBill: each FUNCTION takes parameters, does one job and RETURNs one answer, and finalBill is built by calling the others.',
    difficulty: 'Easy',
    source: RecursionScripts.FunctionBasics,
  },
  {
    id: 'fn-grade-calculator',
    title: 'Grade Calculator',
    category: 'Recursion & Functions',
    description: 'An isValid guard returns TRUE / FALSE, a gradeOf ELSE IF ladder returns the grade as text, and invalid marks (105, -3) are skipped.',
    difficulty: 'Easy',
    source: RecursionScripts.GradeCalculator,
  },
  {
    id: 'fn-parameters-are-copies',
    title: 'Parameters Are Copies',
    category: 'Recursion & Functions',
    description: 'A swap of two parameters changes nothing for the caller, a swap of two array cells does; a changed parameter only counts once it is RETURNed and stored.',
    difficulty: 'Easy',
    source: RecursionScripts.ParametersAreCopies,
  },
  {
    id: 'fn-local-global-scope',
    title: 'Local & Global Scope',
    category: 'Recursion & Functions',
    description: 'A FUNCTION can read a SEQUENCE variable but assigning to it creates a local copy; the two right ways are RETURN and a shared one-cell array.',
    difficulty: 'Medium',
    source: RecursionScripts.LocalAndGlobalScope,
  },
  {
    id: 'fn-prime-toolkit',
    title: 'Prime Toolkit',
    category: 'Recursion & Functions',
    description: 'isPrime is written once and reused by smallestFactor, nextPrimeAfter and countPrimesUpTo: functions built on top of functions.',
    difficulty: 'Medium',
    source: RecursionScripts.PrimeToolkit,
  },
  {
    id: 'fn-class-report',
    title: 'Class Report with Helpers',
    category: 'Recursion & Functions',
    description: 'sumOfMarks, average, indexOfMax, indexOfMin and countAtLeast each do one job over the marks array, highlighting the topper and the lowest score.',
    difficulty: 'Easy',
    source: RecursionScripts.ClassReportFunctions,
  },
  {
    id: 'fn-atm-withdrawal',
    title: 'ATM Withdrawal (Guard Clauses)',
    category: 'Recursion & Functions',
    description: 'A withdraw FUNCTION RETURNs FALSE at the first broken rule (negative, not a multiple of 100, low balance, daily limit), updates the account array and splits the cash into notes.',
    difficulty: 'Medium',
    source: RecursionScripts.AtmWithdrawal,
  },
  {
    id: 'recursion-factorial',
    title: 'Factorial (Recursive)',
    category: 'Recursion & Functions',
    description: 'Base case and recursive case: every call is indented by its depth and pushed on a calls STACK, so the calls wind down to factorial(1) and unwind with the multiplications.',
    difficulty: 'Easy',
    source: RecursionScripts.FactorialRecursion,
  },
  {
    id: 'recursion-head-vs-tail',
    title: 'Before vs After the Call',
    category: 'Recursion & Functions',
    description: 'Printing before the recursive call counts down, printing after it counts up: the same recursion, opposite order. The array is painted from the last cell back.',
    difficulty: 'Easy',
    source: RecursionScripts.HeadVsTailRecursion,
  },
  {
    id: 'recursion-digits',
    title: 'Digits by Recursion',
    category: 'Recursion & Functions',
    description: 'sumDigits, countDigits, reverseDigits (with an accumulator) and digitalRoot peel off the last digit with n % 10 and recurse on the rest.',
    difficulty: 'Easy',
    source: RecursionScripts.DigitRecursion,
  },
  {
    id: 'recursion-power',
    title: 'Slow vs Fast Power',
    category: 'Recursion & Functions',
    description: 'b^e with e calls against exponentiation by squaring, which halves e on every call; a shared array counts the calls of each (11 vs 5 for 2^10).',
    difficulty: 'Medium',
    source: RecursionScripts.PowerRecursion,
  },
  {
    id: 'recursion-gcd-lcm',
    title: 'GCD & LCM (Euclid)',
    category: 'Recursion & Functions',
    description: 'Recursive Euclid gcd(a, b) = gcd(b, a % b) with its call trace, used for square floor tiles, simplifying a fraction and the LCM of two bus timings.',
    difficulty: 'Easy',
    source: RecursionScripts.GcdAndLcm,
  },
  {
    id: 'recursion-fibonacci',
    title: 'Fibonacci Three Ways',
    category: 'Recursion & Functions',
    description: 'Naive double recursion (1973 calls for fib(15)), a memo array that fills in green (31 calls for fib(16)) and a loop that keeps only the last two numbers.',
    difficulty: 'Medium',
    source: RecursionScripts.FibonacciThreeWays,
  },
  {
    id: 'recursion-array',
    title: 'Recursion on an Array',
    category: 'Recursion & Functions',
    description: 'Sum, index of the maximum, count above a limit and an is-sorted check, each written as "this cell plus the answer for the rest of the array".',
    difficulty: 'Easy',
    source: RecursionScripts.ArrayRecursion,
  },
  {
    id: 'recursion-reverse-array',
    title: 'Reverse an Array Recursively',
    category: 'Recursion & Functions',
    description: 'Swap the two ends, then reverse the part in between, until the ends meet: a playlist reversed in place.',
    difficulty: 'Easy',
    source: RecursionScripts.ReverseArrayRecursive,
  },
  {
    id: 'recursion-palindrome',
    title: 'Palindrome Words',
    category: 'Recursion & Functions',
    description: 'Compare the first and last letters with CHAR_AT and recurse inward; non-palindromes print the mismatch and the word built backwards recursively.',
    difficulty: 'Medium',
    source: RecursionScripts.PalindromeRecursion,
  },
  {
    id: 'recursion-number-bases',
    title: 'Binary, Octal & Hex',
    category: 'Recursion & Functions',
    description: 'toBinary(n) = toBinary(n / 2) + the last bit, the same idea for any base up to 16, and counting 1-bits recursively.',
    difficulty: 'Medium',
    source: RecursionScripts.NumberBases,
  },
  {
    id: 'recursion-mutual',
    title: 'Mutual Recursion',
    category: 'Recursion & Functions',
    description: 'isEven and isOdd call each other until n reaches 0, and a Collatz step counter uses isEven.',
    difficulty: 'Medium',
    source: RecursionScripts.MutualRecursion,
  },
  {
    id: 'recursion-hanoi',
    title: 'Tower of Hanoi',
    category: 'Recursion & Functions',
    description: 'Move n - 1 disks aside, move the biggest, move the n - 1 back on top: three STACK pegs, every move printed, 2^n - 1 moves in total.',
    difficulty: 'Hard',
    source: RecursionScripts.TowerOfHanoi,
  },
  {
    id: 'recursion-subsets',
    title: 'Subsets Within a Budget',
    category: 'Recursion & Functions',
    description: 'Backtracking: skip or take each topping, undo the choice on the way back, and prune a branch as soon as it goes over budget.',
    difficulty: 'Hard',
    source: RecursionScripts.SubsetsWithinBudget,
  },
  {
    id: 'recursion-permutations',
    title: 'Seating Permutations',
    category: 'Recursion & Functions',
    description: 'Every seating order of three friends by swapping each one into the next seat, recursing and swapping back; n! arrangements.',
    difficulty: 'Hard',
    source: RecursionScripts.SeatingPermutations,
  },
  {
    id: 'recursion-n-queens',
    title: 'N-Queens',
    category: 'Recursion & Functions',
    description: 'Place one queen per row, check columns and diagonals with isSafe, recurse, and remove the queen to try the next column; both 4 x 4 boards are printed.',
    difficulty: 'Hard',
    source: RecursionScripts.NQueens,
  },
  {
    id: 'recursion-climbing-stairs',
    title: 'Climbing Stairs',
    category: 'Recursion & Functions',
    description: 'ways(n) = ways(n - 1) + ways(n - 2) with a memo array, plus a recursion that lists every way to climb as 1+2+1 text.',
    difficulty: 'Medium',
    source: RecursionScripts.ClimbingStairs,
  },
  {
    id: 'recursion-coin-change',
    title: 'Coin Change',
    category: 'Recursion & Functions',
    description: 'Count the ways to pay an amount (use a coin again or move on) and find the fewest coins with a memo table, then read the coins back out of it.',
    difficulty: 'Hard',
    source: RecursionScripts.CoinChangeWays,
  },
  // ── Layout & Camera ─────────────────────────────────────────────────────────
  {
    id: 'layout-array-line',
    title: 'Array Line Spacing',
    category: 'Layout & Camera',
    description: 'Set the spacing of an array with LAYOUT ... AS LINE, then highlight one element.',
    difficulty: 'Easy',
    source: LayoutScripts.ArrayLineSpacing,
  },
  {
    id: 'layout-horizontal-stack',
    title: 'Horizontal Stack',
    category: 'Layout & Camera',
    description: 'Stacks stand vertical by default; LINE with axis=horizontal lays one out as a row.',
    difficulty: 'Easy',
    source: LayoutScripts.HorizontalStack,
  },
  {
    id: 'layout-ring',
    title: 'Ring of Values',
    category: 'Layout & Camera',
    description: 'Arrange an array on a CIRCULAR ring and light each element in turn.',
    difficulty: 'Easy',
    source: LayoutScripts.RingOfValues,
  },
  {
    id: 'layout-grid',
    title: 'Array as a Matrix',
    category: 'Layout & Camera',
    description: 'GRID turns a flat array into three rows of three, and the corners and centre are marked.',
    difficulty: 'Easy',
    source: LayoutScripts.ArrayAsMatrix,
  },
  {
    id: 'layout-graph-ring',
    title: 'Graph: Physics to Ring',
    category: 'Layout & Camera',
    description: 'Build a cycle under FORCE_DIRECTED, then freeze it into a CIRCULAR ring mid-run.',
    difficulty: 'Medium',
    source: LayoutScripts.GraphPhysicsToRing,
  },
  {
    id: 'layout-tree-spacing',
    title: 'Tree Level and Sibling Gaps',
    category: 'Layout & Camera',
    description: 'HIERARCHY with explicit levelGap and siblingGap on a seven-node search tree.',
    difficulty: 'Easy',
    source: LayoutScripts.TreeSpacing,
  },
  {
    id: 'camera-focus',
    title: 'Camera Focus on One Structure',
    category: 'Layout & Camera',
    description: 'CAMERA FOCUS points the camera at the tree, then at the array, then back to AUTO_FIT.',
    difficulty: 'Medium',
    source: LayoutScripts.CameraFocusTwoStructures,
  },
  {
    id: 'camera-orbit',
    title: 'Camera Orbit',
    category: 'Layout & Camera',
    description: 'CAMERA ORBIT(15) turns slowly around the tree while two values are inserted.',
    difficulty: 'Easy',
    source: LayoutScripts.CameraOrbit,
  },
  {
    id: 'camera-fixed-angle',
    title: 'Fixed Camera Angle',
    category: 'Layout & Camera',
    description: 'CAMERA POSITION pins the camera at an absolute point and turns automatic follow off.',
    difficulty: 'Easy',
    source: LayoutScripts.CameraFixedAngle,
  },
  {
    id: 'layout-pin-release',
    title: 'Pin and Release an Element',
    category: 'Layout & Camera',
    description: 'POSITION lifts one element out of its row; an empty AT () drops it back.',
    difficulty: 'Medium',
    source: LayoutScripts.PinAndRelease,
  },
  {
    id: 'layout-custom',
    title: 'Manual Placement',
    category: 'Layout & Camera',
    description: 'LAYOUT ... AS CUSTOM() disables automatic placement, so each element gets its own POSITION.',
    difficulty: 'Medium',
    source: LayoutScripts.ManualPlacement,
  },
];

// ── Derived helpers ────────────────────────────────────────────────────────────

/** Ordered list of all distinct categories (preserves insertion order). */
export const EXAMPLE_CATEGORIES: ExampleCategory[] = [
  ...new Set(EXAMPLES.map(e => e.category)),
] as ExampleCategory[];

/** Look up a single example by its stable id. */
export function getExampleById(id: string): Example | undefined {
  return EXAMPLES.find(e => e.id === id);
}

/** All examples belonging to a given category. */
export function getExamplesByCategory(category: ExampleCategory): Example[] {
  return EXAMPLES.filter(e => e.category === category);
}
