import type { Member, MemberId, TaskSeed } from './types';

export const MEMBERS: Member[] = [
  { id: 'manas', name: 'Manas Shah', role: 'Project & architecture lead', area: 'AQVL Core roadmap', tool: 'Claude Code' },
  { id: 'yash', name: 'Yash Poojari', role: 'Technical contributor', area: 'Temporary AI API proof of concept', tool: 'Antigravity' },
  { id: 'tirrth', name: 'Tirrth Mistry', role: 'Visual & UX contributor', area: 'Animation, interaction & visual polish', tool: 'Antigravity' },
  { id: 'pranav', name: 'Pranav Adigare', role: 'Docs, testing & IP support', area: 'Documentation, test evidence, patent research', tool: 'Manual + docs' },
];

export const MEMBER_BY_ID: Record<MemberId, Member> = Object.fromEntries(MEMBERS.map((m) => [m.id, m])) as Record<MemberId, Member>;

export interface Guardrails {
  mission: string;
  inScope: string[];
  outOfScope: string[];
}

export const GUARDRAILS: Record<Exclude<MemberId, 'manas'>, Guardrails> = {
  yash: {
    mission:
      'A temporary teacher demo: a user types a concept, an API returns valid AQVL, and the existing pipeline visualizes it. This is a proof of concept, not the final AI architecture.',
    inScope: [
      'New code under poc/ai-api/ and docs/poc-ai-api/ only',
      'Calling the compiler through its existing public exports (read-only use)',
      'Prompt templates, few-shot examples, the API server, the validate-and-retry loop',
      'The RS mini-project: new code under poc/rs/ and docs/poc-rs/ only — a standalone, deletable MCQ-based recommender, reachable behind its own route and not linked from the main nav',
    ],
    outOfScope: [
      'Any edit to packages/compiler, packages/runtime, packages/renderer, packages/shared',
      'AQIR, the VM, execution architecture, centralized semantic contracts',
      'Refactors of any existing file; Playground changes without Manas\'s written approval',
      'Committing API keys (env vars only, .env stays git-ignored)',
      'Wiring RS into the main Playground/nav, or making it hard to delete — it must stay a self-contained, removable experiment',
    ],
  },
  tirrth: {
    mission:
      'Raise the quality of what people see today: motion, timing, camera, spacing, color states, feedback and loading/error states, without touching how AQVL computes anything.',
    inScope: [
      'Presentation constants and styling in packages/renderer/src/components/** (easing, durations, colors, sizes)',
      'Theme tokens in packages/shared/src/theme/**',
      'Playground UI and CSS in packages/demo/src/** (not the compiler/runtime calls)',
    ],
    outOfScope: [
      'packages/compiler, packages/runtime, AQIR, the VM, scene data contracts',
      'Changing what data the renderer receives, or adding new scene fields',
      'Architectural refactors of renderer components (e.g. GenericSceneRenderer props) — that is Roadmap Phase 2.3',
    ],
  },
  pranav: {
    mission:
      'Take documentation, test evidence, issue write-ups and patent/IP preparation off the development critical path, with every claim traceable to the repo or a cited source.',
    inScope: [
      'New files under docs/architecture, docs/testing, docs/ip, docs/experiments',
      'Running the existing test suite and the Playground; recording results',
      'Patent prior-art searching on public databases (Google Patents, Lens.org, Espacenet)',
    ],
    outOfScope: [
      'Editing source code or tests to make results pass',
      'Filing anything with a patent office, or presenting drafts as legal advice',
      'Recording a result that was not actually observed',
    ],
  },
};

const t = (seed: Omit<TaskSeed, 'kind' | 'status'> & Partial<Pick<TaskSeed, 'status'>>): TaskSeed => ({
  kind: 'team',
  status: 'planned',
  ...seed,
  // Team tasks are deliberately undated: the page logs when each one is finished, nothing more.
  deadline: null,
});

export const TEAM_TASKS: TaskSeed[] = [
  // ─── Yash: temporary AI API proof of concept ──────────────────────────
  t({
    id: 'Y1', owner: 'yash', order: 1, area: 'Contract',
    title: 'Define the AQVL output contract for the PoC',
    objective: 'Pin down exactly which subset of AQVL the API is allowed to emit, so generated code has a fixed, checkable target.',
    scope: 'Read docs/grammar.md, docs/LANGUAGE_SPEC.md and 10 examples from packages/demo/src/examples/registry.ts (2 each: sorting, searching, trees, graphs, loops). List the allowed statements, structures and required program skeleton (SCENE / DECLARE / SEQUENCE / END).',
    outOfScope: 'No code. No changes to the grammar or compiler.',
    priority: 'P0', deadline: '2026-09-30', dependencies: [],
    expectedOutcome: 'docs/poc-ai-api/aqvl-output-contract.md',
    definitionOfDone: 'Contract lists allowed keywords and structures, a program skeleton, and 3 reference programs copied from the registry that satisfy it; Manas has read it.',
    verification: 'Each of the 3 reference programs compiles without errors in the Playground.',
    notes: '',
  }),
  t({
    id: 'Y2', owner: 'yash', order: 2, area: 'Validation',
    title: 'Build a standalone AQVL validation harness',
    objective: 'A function that takes AQVL text and reports whether it compiles, using the compiler as-is.',
    scope: 'poc/ai-api/validate.ts: run Lexer → Parser → SemanticValidator → AQIRGenerator via the public @aqvl/compiler exports (same sequence App.tsx uses); return { valid, stage, errors[] }. Include a CLI: npx tsx poc/ai-api/validate.ts file.aqvl.',
    outOfScope: 'No edits inside packages/compiler. No new compiler exports.',
    priority: 'P0', deadline: '2026-10-02', dependencies: ['Y1'],
    expectedOutcome: 'poc/ai-api/validate.ts plus a short README section on usage',
    definitionOfDone: 'Harness returns valid=true for the 3 Y1 reference programs and valid=false with a readable error for 3 deliberately broken programs.',
    verification: 'Six-case check committed as poc/ai-api/validate.test.ts and passing.',
    notes: '',
  }),
  t({
    id: 'Y3', owner: 'yash', order: 3, area: 'Prompting',
    title: 'Write the prompt template and few-shot set',
    objective: 'A system prompt plus examples that make an LLM emit contract-conforming AQVL for a topic.',
    scope: 'poc/ai-api/prompt.ts: system prompt restating the Y1 contract; 8 few-shot pairs (topic → AQVL) taken from real registry examples, not invented code.',
    outOfScope: 'No fine-tuning, no vector stores, no agent frameworks.',
    priority: 'P0', deadline: '2026-10-04', dependencies: ['Y1'],
    expectedOutcome: 'poc/ai-api/prompt.ts with 8 few-shot pairs',
    definitionOfDone: 'All 8 few-shot AQVL programs pass the Y2 harness.',
    verification: 'Script that runs every few-shot program through validate.ts shows 8/8 valid.',
    notes: 'Can be drafted in parallel with Y2; final check needs Y2.',
  }),
  t({
    id: 'Y4', owner: 'yash', order: 4, area: 'API',
    title: 'Stand up the minimal /generate endpoint',
    objective: 'POST /generate { topic } returns { aqvl } from one LLM call.',
    scope: 'poc/ai-api/server.ts: small Node HTTP server (no framework needed), provider key read from an env var, 30 s timeout, JSON errors. .env.example committed; .env git-ignored.',
    outOfScope: 'No auth system, database, or deployment. No key in the repo.',
    priority: 'P0', deadline: '2026-10-07', dependencies: ['Y3'],
    expectedOutcome: 'Running local server with one endpoint',
    definitionOfDone: 'curl with topic "bubble sort" returns an aqvl string; a missing key returns a clear 500 JSON error.',
    verification: 'Both curl calls recorded in docs/poc-ai-api/server-check.md; git grep shows no key material.',
    notes: '',
  }),
  t({
    id: 'Y5', owner: 'yash', order: 5, area: 'Validation',
    title: 'Add the validate-and-retry loop',
    objective: 'Only return AQVL that actually compiles, repairing it with compiler feedback when it does not.',
    scope: 'In server.ts, pass the model output through validate.ts; on failure resend the compiler errors, max 2 retries. Response: { aqvl, valid, attempts, errors }.',
    outOfScope: 'No compiler changes to make generated code pass.',
    priority: 'P0', deadline: '2026-10-09', dependencies: ['Y2', 'Y4'],
    expectedOutcome: 'Endpoint that reports valid/attempts honestly',
    definitionOfDone: 'An invalid first answer is retried; after 3 failed attempts the API returns valid=false with the last errors instead of broken code marked valid.',
    verification: 'Unit test with a stubbed model that fails once then succeeds, and one that always fails.',
    notes: '',
  }),
  t({
    id: 'Y6', owner: 'yash', order: 6, area: 'Evaluation',
    title: 'Run a 20-topic evaluation and report the pass rate',
    objective: 'Know, with numbers, how reliable the PoC is before showing teachers.',
    scope: '20 teacher-style topics (e.g. bubble sort, binary search, BST insert, BFS, stack push/pop, factorial recursion). Run each once; record valid, attempts, and whether the Playground visual matches the topic (manual check).',
    outOfScope: 'No prompt tuning mid-run; tune after, then re-run as a new row.',
    priority: 'P1', deadline: '2026-10-12', dependencies: ['Y5'],
    expectedOutcome: 'docs/poc-ai-api/eval-report.md with a 20-row table and pass rate',
    definitionOfDone: 'Report shows compile-pass rate and visual-correctness rate separately, with every failure listed.',
    verification: 'Manas spot-checks 3 rows by rerunning them.',
    notes: '',
  }),
  t({
    id: 'Y7', owner: 'yash', order: 7, area: 'Hand-off',
    title: 'Build the topic → Playground demo page',
    objective: 'A teacher can type a topic and get to the visualization in two clicks.',
    scope: 'poc/ai-api/demo.html: topic input, calls /generate, shows code, "Copy code" and "Open Playground" (opens #/playground in a new tab; teacher pastes). Any change to the Playground itself needs Manas\'s approval first.',
    outOfScope: 'No edits to packages/demo unless approved in writing.',
    priority: 'P1', deadline: '2026-10-15', dependencies: ['Y5'],
    expectedOutcome: 'Working local demo page',
    definitionOfDone: 'End to end: topic → code → pasted into Playground → animation runs, for 3 topics.',
    verification: 'Screen recording of the 3 topics saved to docs/poc-ai-api/.',
    notes: '',
  }),
  t({
    id: 'Y8', owner: 'yash', order: 8, area: 'Demo',
    title: 'Teacher demo script and known-limitations note',
    objective: 'A repeatable 5-minute demo and an honest list of what the PoC cannot do.',
    scope: 'docs/poc-ai-api/demo-script.md: setup steps, 3 safe topics (from Y6 passes), talking points; limitations section built from Y6 failures.',
    outOfScope: 'No claims beyond what Y6 measured.',
    priority: 'P1', deadline: '2026-10-17', dependencies: ['Y6', 'Y7'],
    expectedOutcome: 'docs/poc-ai-api/demo-script.md',
    definitionOfDone: 'Someone other than Yash can run the demo from the script alone.',
    verification: 'Pranav or Tirrth follows the script once and reports it worked.',
    notes: '',
  }),

  // ─── Yash: RS mini-project (MCQ-based DS recommender) ─────────────────
  // Small, deletable side project; the API/diagnostic logic matters more than the UI.
  t({
    id: 'RS1', owner: 'yash', order: 9, area: 'RS · Design',
    title: 'MCQ question bank and scoring rubric',
    objective: 'A fixed set of 5–10 MCQs that separate students by comfort with core DS concepts (arrays, recursion, trees, graphs, complexity), plus a scoring rubric mapping answers to a skill profile.',
    scope: 'docs/poc-rs/question-bank.md: each question, its options, which skill dimension it probes, and the point weight per option. Base dimensions on the same category list used by the example registry (arrays, recursion, trees, graphs, hashing) so recommendations can point at real registry examples later.',
    outOfScope: 'No code yet. No adaptive/branching logic — a fixed question set only.',
    priority: 'P1', deadline: '2026-10-05', dependencies: [],
    expectedOutcome: 'docs/poc-rs/question-bank.md',
    definitionOfDone: '5–10 questions exist, each tagged with a skill dimension and scoring weights; Manas has read it.',
    verification: 'Manual hand-scoring of 2 sample answer sets matches the documented rubric.',
    notes: 'Can run in parallel with Y1–Y3; shares no code with the AI-API pipeline.',
  }),
  t({
    id: 'RS2', owner: 'yash', order: 10, area: 'RS · Engine',
    title: 'Diagnostic scoring engine',
    objective: 'Turn a set of MCQ answers into a skill profile (per-dimension score) using the RS1 rubric, as a pure, testable function.',
    scope: 'poc/rs/score.ts: takes answers[], returns a per-dimension score plus an overall weakest-dimension ranking, implementing the RS1 rubric exactly (no new weighting invented ad hoc).',
    outOfScope: 'No UI. No recommendation logic yet (that is RS3).',
    priority: 'P1', deadline: '2026-10-08', dependencies: ['RS1'],
    expectedOutcome: 'poc/rs/score.ts plus poc/rs/score.test.ts',
    definitionOfDone: 'Given 4 hand-constructed answer sets (strong, weak, mixed, all-skipped), the engine produces the scores a manual hand-calculation predicts.',
    verification: 'score.test.ts passing with the 4 hand-checked cases.',
    notes: '',
  }),
  t({
    id: 'RS3', owner: 'yash', order: 11, area: 'RS · Recommendation',
    title: 'DS + error-pattern recommendation mapping',
    objective: 'Map a skill profile to a concrete next data structure/topic to study, and separately, map a student\'s logged mistake pattern (once Phase 3.5\'s error catalogue exists) to a targeted follow-up recommendation.',
    scope: 'poc/rs/recommend.ts: (a) weakest-dimension-to-topic mapping table, referencing real packages/demo/src/examples/registry.ts categories/ids so a recommendation can link straight to a runnable example; (b) a second, separate mapping from a Phase 3.5 logical-error rule id (see docs/design/phase3.5-logical-error-catalogue.md once it exists) to a targeted remedial topic, kept as an independent table so it can be filled in incrementally as that catalogue grows.',
    outOfScope: 'No machine learning / no adaptive model — table-driven mapping only. No changes to Phase 3.5 code itself.',
    priority: 'P1', deadline: '2026-10-13', dependencies: ['RS2'],
    expectedOutcome: 'poc/rs/recommend.ts with both mapping tables and unit tests',
    definitionOfDone: 'For every RS1 skill dimension there is at least one recommended registry example; the error-pattern table has at least 3 entries stubbed even if the Phase 3.5 catalogue is not finished yet.',
    verification: 'recommend.test.ts covers one case per skill dimension and asserts the returned example id exists in the registry.',
    notes: 'The error-pattern half depends on Phase 3.5\'s rule catalogue for real ids; stub with placeholder rule names until then and revisit once 3.5.2 lands.',
  }),
  t({
    id: 'RS4', owner: 'yash', order: 12, area: 'RS · Demo',
    title: 'Minimal /rs route and delete-readiness check',
    objective: 'A working, self-contained MCQ-to-recommendation flow behind its own route, built so it can be deleted in one commit if the mini-project is dropped.',
    scope: 'A single new route (e.g. #/rs) under packages/demo/src/pages/rs/, isolated to that folder plus poc/rs/: renders the RS1 questions, scores with RS2, shows the RS3 recommendation with a link to the suggested example. No shared state or imports from packages/demo/src/pages/tasks or Playground beyond routing.',
    outOfScope: 'No edits to Router.tsx beyond adding the one route entry. No promotion to the main nav without Manas\'s sign-off.',
    priority: 'P2', deadline: '2026-10-18', dependencies: ['RS3'],
    expectedOutcome: 'A working #/rs demo page',
    definitionOfDone: 'End to end: answer the MCQs, see a scored profile, see a recommendation with a working link to a real example, for at least 2 different answer patterns.',
    verification: 'A short note in docs/poc-rs/delete-check.md confirming the entire feature can be removed by deleting packages/demo/src/pages/rs/, poc/rs/, docs/poc-rs/ and the one Router.tsx line — verified by actually doing it on a throwaway branch and confirming the rest of the app still builds.',
    notes: '',
  }),

  // ─── Tirrth: visual experience ────────────────────────────────────────
  t({
    id: 'T1', owner: 'tirrth', order: 1, area: 'Audit',
    title: 'Visual audit of the current Playground',
    objective: 'A concrete, prioritized list of what looks or feels wrong today, so every later task fixes something observed.',
    scope: 'Run 12 examples (2 each: sorting, searching, trees, graphs, linked lists, hash maps) in light and dark themes. Screenshot each at start, mid-run and end. Log issues: example, moment, what\'s wrong, severity (high/med/low).',
    outOfScope: 'No fixes in this task.',
    priority: 'P0', deadline: '2026-09-30', dependencies: [],
    expectedOutcome: 'docs/ux/visual-audit-2026-09.md with screenshots',
    definitionOfDone: 'At least 12 examples covered in both themes; every issue has a severity and a screenshot.',
    verification: 'Manas reviews and tags which issues map to T2–T7.',
    notes: '',
  }),
  t({
    id: 'T2', owner: 'tirrth', order: 2, area: 'Animation',
    title: 'Tune swap and compare motion timing',
    objective: 'Swaps and comparisons read clearly: no jarring snaps, no dragging.',
    scope: 'Presentation constants only in packages/renderer/src/components/array/arrayEasing.ts and swapMotionPath.ts (durations, easing curves, arc height).',
    outOfScope: 'No changes to when steps happen (runtime/scheduler) or to scene data.',
    priority: 'P1', deadline: '2026-10-03', dependencies: ['T1'],
    expectedOutcome: 'Adjusted constants with a before/after clip for bubble and quick sort',
    definitionOfDone: 'T1 motion issues for sorting are resolved or explicitly deferred; existing tests pass.',
    verification: 'arrayEasing.test.ts and swapMotionPath.test.ts pass (update expected values only where the constant intentionally changed).',
    notes: '',
  }),
  t({
    id: 'T3', owner: 'tirrth', order: 3, area: 'Camera',
    title: 'Fix camera framing and jumps found in the audit',
    objective: 'Elements never clip off-screen and the camera never jumps abruptly during auto-fit.',
    scope: 'Framing padding, damping and transition parameters in CameraController.tsx and ArrayCameraChoreographer.ts for the specific cases logged in T1.',
    outOfScope: 'No new camera modes; no changes to BaseCameraChoreographer\'s interface.',
    priority: 'P1', deadline: '2026-10-07', dependencies: ['T1'],
    expectedOutcome: 'Camera fixes for each T1 camera issue',
    definitionOfDone: 'Every T1 camera issue re-checked and passing; no new clipping on the 12 audit examples.',
    verification: 'CameraController.test.tsx and ArrayCameraChoreographer.test.ts pass.',
    notes: 'Manas has recent in-progress edits in these files; pull latest main and coordinate before starting.',
  }),
  t({
    id: 'T4', owner: 'tirrth', order: 4, area: 'Color & state',
    title: 'Contrast pass on element state colors',
    objective: 'Every element state (default, compared, swapped, sorted, highlighted, error) is distinguishable and readable in both themes.',
    scope: 'Tokens in packages/shared/src/theme/semanticColors.ts and highlightStyle.ts. Check label-on-fill contrast ≥ 4.5:1 (WCAG AA) per state and theme.',
    outOfScope: 'No new states; no changes to which state the runtime assigns.',
    priority: 'P1', deadline: '2026-10-09', dependencies: ['T1'],
    expectedOutcome: 'Updated tokens plus a contrast table in docs/ux/state-contrast.md',
    definitionOfDone: 'All state/theme pairs ≥ 4.5:1, or a documented exception with reason.',
    verification: 'semanticColors.test.ts and highlightStyle.test.ts pass; contrast table lists measured ratios.',
    notes: '',
  }),
  t({
    id: 'T5', owner: 'tirrth', order: 5, area: 'Layout & spacing',
    title: 'Node label and edge label legibility for trees and graphs',
    objective: 'Values and edge weights stay readable at default zoom on the largest tree and graph examples.',
    scope: 'Label size, offset and background in packages/renderer/src/components/generic/PrimitiveNode.tsx and PrimitiveEdge.tsx.',
    outOfScope: 'No layout algorithm changes (runtime layout strategies are Core).',
    priority: 'P2', deadline: '2026-10-13', dependencies: ['T4'],
    expectedOutcome: 'Label styling changes with before/after screenshots',
    definitionOfDone: 'No overlapping labels on Dijkstra, Kruskal and BST delete examples at default camera.',
    verification: 'GenericSceneRenderer.test.tsx passes; screenshots attached.',
    notes: '',
  }),
  t({
    id: 'T6', owner: 'tirrth', order: 6, area: 'States',
    title: 'Playground loading, empty and compile-error states',
    objective: 'The user always knows what is happening: loading, nothing to show, or what went wrong and where.',
    scope: 'packages/demo/src/pages/Playground.tsx UI and playground.css: loading indicator, empty-canvas message, compile error panel with line number.',
    outOfScope: 'No change to how compilation runs or what errors the compiler produces.',
    priority: 'P1', deadline: '2026-10-15', dependencies: ['T1'],
    expectedOutcome: 'Three designed states in the Playground',
    definitionOfDone: 'Each state reachable and screenshotted: fresh load, cleared editor, a program with a syntax error.',
    verification: 'playground.compile.test.tsx passes; manual check of the three states in both themes.',
    notes: '',
  }),
  t({
    id: 'T7', owner: 'tirrth', order: 7, area: 'Interaction feedback',
    title: 'Playback control feedback and keyboard focus',
    objective: 'Play, pause, step and reset controls show hover, pressed, disabled and focus states clearly.',
    scope: 'Styles for Playground playback controls; visible focus ring; disabled styling when no program is loaded.',
    outOfScope: 'No new controls; no change to playback logic.',
    priority: 'P2', deadline: '2026-10-17', dependencies: ['T6'],
    expectedOutcome: 'Consistent control states across themes',
    definitionOfDone: 'All controls usable by keyboard alone with a visible focus ring.',
    verification: 'Keyboard-only walkthrough recorded in docs/ux/controls-check.md.',
    notes: '',
  }),
  t({
    id: 'T8', owner: 'tirrth', order: 8, area: 'Audit',
    title: 'Before/after verification pass',
    objective: 'Prove the visual work improved the product on the same examples used in the audit.',
    scope: 'Re-capture the T1 set; mark each T1 issue fixed, deferred or regressed.',
    outOfScope: 'No new fixes during this pass; log new issues for the next cycle.',
    priority: 'P1', deadline: '2026-10-20', dependencies: ['T2', 'T3', 'T4', 'T5', 'T6', 'T7'],
    expectedOutcome: 'docs/ux/visual-audit-followup.md',
    definitionOfDone: 'Every T1 issue has a final state and side-by-side screenshots.',
    verification: 'Full demo test suite passes (pnpm --filter demo test).',
    notes: '',
  }),

  // ─── Pranav: docs, testing, IP, support ───────────────────────────────
  t({
    id: 'P1', owner: 'pranav', order: 1, area: 'Testing',
    title: 'First regression evidence entry',
    objective: 'A dated, commit-pinned record of the test suite result, repeated weekly.',
    scope: 'Run pnpm test at the repo root; record date, commit hash, totals per package and any failures in docs/testing/regression-log.md. Add a new entry every Monday.',
    outOfScope: 'No fixing of failing tests.',
    priority: 'P0', deadline: '2026-09-29', dependencies: [],
    expectedOutcome: 'docs/testing/regression-log.md with its first entry',
    definitionOfDone: 'Entry has commit hash, date, counts and failure names copied from real output.',
    verification: 'Manas reruns the suite at the same commit and gets the same counts.',
    notes: '',
  }),
  t({
    id: 'P2', owner: 'pranav', order: 2, area: 'Testing',
    title: 'Test inventory',
    objective: 'Know what the ~94 test files actually cover.',
    scope: 'For every *.test.ts(x) in the repo: package, file, what it tests (one line), number of tests.',
    outOfScope: 'No new tests.',
    priority: 'P1', deadline: '2026-10-01', dependencies: [],
    expectedOutcome: 'docs/testing/test-inventory.md',
    definitionOfDone: 'Every test file listed; totals match the P1 run.',
    verification: 'File count matches find . -name "*.test.ts*" (excluding node_modules).',
    notes: '',
  }),
  t({
    id: 'P3', owner: 'pranav', order: 3, area: 'Documentation',
    title: 'Architecture overview document',
    objective: 'One readable description of the pipeline for new contributors and the patent work.',
    scope: 'docs/architecture/overview.md: Lexer → Parser → Semantic → Optimizer → AQIR → VM → Renderer, one section per package with key files, drawn from README.md, docs/LANGUAGE_SPEC.md and the source tree.',
    outOfScope: 'No describing planned features as existing.',
    priority: 'P1', deadline: '2026-10-03', dependencies: [],
    expectedOutcome: 'docs/architecture/overview.md',
    definitionOfDone: 'Every file path mentioned exists; Manas marks it accurate.',
    verification: 'Manas review; path check by script or manual open.',
    notes: '',
  }),
  t({
    id: 'P4', owner: 'pranav', order: 4, area: 'Support',
    title: 'Experiment record template and back-fill',
    objective: 'Keep experiment evidence (acid tests, verification reports) in one consistent format.',
    scope: 'docs/experiments/TEMPLATE.md (question, setup, result, evidence link); back-fill entries for acid-test-report.md and backend-enrichment-verification-report.md, using only what those reports state.',
    outOfScope: 'No new experiments.',
    priority: 'P2', deadline: '2026-10-05', dependencies: [],
    expectedOutcome: 'Template plus 2 back-filled records',
    definitionOfDone: 'Each back-filled field traces to a sentence in the source report.',
    verification: 'Spot-check by Manas.',
    notes: '',
  }),
  t({
    id: 'P5', owner: 'pranav', order: 5, area: 'Testing',
    title: 'Manual Playground test plan and first execution',
    objective: 'Cover user-facing behavior the automated suite does not.',
    scope: '25 manual cases: load example, run, pause, step, reset, theme switch, syntax error, empty editor, long program, each category. Execute all once and record pass/fail.',
    outOfScope: 'No fixes.',
    priority: 'P1', deadline: '2026-10-07', dependencies: ['P2'],
    expectedOutcome: 'docs/testing/playground-manual-test-plan.md with results',
    definitionOfDone: '25 cases with steps, expected result, actual result.',
    verification: 'Tirrth reruns 3 cases and confirms.',
    notes: '',
  }),
  t({
    id: 'P6', owner: 'pranav', order: 6, area: 'IP',
    title: 'Patent prior-art search, round 1',
    objective: 'Find what already exists before claiming novelty.',
    scope: 'Search Google Patents, Lens.org and Espacenet for: algorithm visualization languages, code-to-animation compilation, declarative layout in visualization DSLs, intermediate representations for animation. Log at least 15 references.',
    outOfScope: 'No legal conclusions.',
    priority: 'P1', deadline: '2026-10-08', dependencies: [],
    expectedOutcome: 'docs/ip/prior-art-log.md',
    definitionOfDone: '≥ 15 rows: number/link, title, date, assignee, what it covers, how AQVL differs.',
    verification: 'Every row has a working link.',
    notes: '',
  }),
  t({
    id: 'P7', owner: 'pranav', order: 7, area: 'Testing',
    title: 'Issue drafts from test failures',
    objective: 'Turn every observed failure into an actionable, reproducible issue.',
    scope: 'For each failure in P1 and P5: title, steps to reproduce, expected vs actual, commit, severity.',
    outOfScope: 'No speculative root causes.',
    priority: 'P1', deadline: '2026-10-10', dependencies: ['P1', 'P5'],
    expectedOutcome: 'docs/testing/issue-drafts.md',
    definitionOfDone: 'Every failure from P1/P5 has an entry; Manas can paste each into GitHub unchanged.',
    verification: 'Manas reproduces 2 issues from the steps alone.',
    notes: '',
  }),
  t({
    id: 'P8', owner: 'pranav', order: 8, area: 'IP',
    title: 'Candidate novelty statements',
    objective: 'Draft 3–5 statements of what may be new in AQVL, checked against prior art.',
    scope: 'Using P3 and P6: candidates such as layout as a language feature, a spatial AQIR instruction set, algorithm-and-layout co-compilation. Each with nearest prior art and the distinguishing element.',
    outOfScope: 'Not legal advice; no filing.',
    priority: 'P1', deadline: '2026-10-14', dependencies: ['P3', 'P6'],
    expectedOutcome: 'docs/ip/novelty-candidates.md',
    definitionOfDone: 'Each statement cites ≥ 1 prior-art row and ≥ 1 repo file.',
    verification: 'Manas review.',
    notes: '',
  }),
  t({
    id: 'P9', owner: 'pranav', order: 9, area: 'IP',
    title: 'Invention disclosure draft',
    objective: 'A complete disclosure pack ready for a patent professional to review.',
    scope: 'Problem, summary, detailed description (from P3), figure list, embodiments, inventors, prior art (P6), candidate claims area (P8).',
    outOfScope: 'No filing; no final claim language.',
    priority: 'P2', deadline: '2026-10-21', dependencies: ['P8'],
    expectedOutcome: 'docs/ip/invention-disclosure-draft.md',
    definitionOfDone: 'All sections filled; open questions listed explicitly.',
    verification: 'Manas sign-off.',
    notes: '',
  }),
];
